### ISSUE TITLE
Add Canny edge detection function

### ISSUE THREAD

**Issue by kmsquire** [timholy/Images.jl#143]
Most of the basic functions needed (Gaussian filtering, gradient calculation, and non-maximal suppression) already exist, and just need to be strung together.

This would be an easy way for someone who is just starting to work with `Images.jl` to make a contribution.

**Comment by siddhantjain** [comment]
Hi, is anyone working on this? I was thinking to do this to get started on working with Images.jl.

**Comment by kmsquire** [comment]
Go for it!

**Comment by siddhantjain** [comment]
@kmsquire  I just created PR for an implementation of canny. Can you please review it?

#441

**Comment by timholy** [comment]
Closed by #441
