### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by aliock** [timholy/Images.jl#198]
Hi! When I do img = testimage("mandrill") I get the following

```
ERROR: error compiling imread: error compiling imread: could not load module : dlopen(.dylib, 1): image not found
 in testimage at /Users/goncalovaladao/.julia/v0.3/TestImages/src/TestImages.jl:22
```

When I do using TestImages I get

```
WARNING: ImageMagick utilities not found. Install for more file format support.
```

When I added Images and ImageView I had an error regarding a dependency called  libwand 

I searched for similar problems of users of Images and ImageView and I found them but nonetheless the proposed solutions do not seem to apply in my case.

Thank you very much!

**Comment by timholy** [comment]
Closing due to lack of feedback. Feel free to reopen if this is still an issue you want resolved.
