### ISSUE TITLE
Why is grayscale image defined as Gray{UfixedBase{Uint8,8}?

### ISSUE THREAD

**Issue by philtomson** [timholy/Images.jl#233]
I've read in a grayscale image which has the following attributes:
    julia> cimg
    Gray Image with:
      data: 1920x1080 Array{Gray{UfixedBase{Uint8,8}},2}
      properties:
       IMcs: Gray
        spatialorder:  x y
        pixelspacing:  1 1

It's an array of Ufixed8 meaning values between 0 and 1. for example:

    julia> cimg[1,1]
Gray{Ufixed8}(0.541)

I'd like my grayscale values to range from 0 to 255 (so I could do a histogram on the image, for example). Is there a way to convert to an array of values between 0 and 255?

**Comment by elsuizo** [comment]
Hello Tim, linspace should not be?¿
```julia
 linspace(FixedPointNumbers.Ufixed8(0),FixedPointNumbers.Ufixed8(1),256)
```
I Tried the following function for the histogram:
```julia
function histogram3(img)
    vals = linspace(FixedPointNumbers.Ufixed8(0),FixedPointNumbers.Ufixed8(1),256)
    h = Array(Float64,256)
    m,n = size(img)
    N = m * n
    for l = 1:length(vals)
        counter = 0.0
        @nloops 2 i img begin
            if((@nref 2 img i) == vals[l])
                counter += 1.0
            end
            h[l] = counter
        end
    end
    return h ./ N
end
```

**Comment by timholy** [comment]
You should be able to do that as
```
_, counts = hist(img[:], -1/256:1/256:1)
```
and it will be much faster.
