### ISSUE TITLE
Feature request: Add `AlphaColorValue` and `AlphaColor` to math for `AbstractGray`.

### ISSUE THREAD

**Issue by twadleigh** [timholy/Images.jl#239]
With the RGB math in `Images.jl`, `Interpolations.jl` works like a charm on, e.g., `RGBA` images. However, the same is not true for `GrayAlpha` images.

It looks like the math is more extensive for `AbstractRGB` than it is for `AbstractGray`.

I may try my hand at putting together a PR to bring `AbstractGray` up to parity with `AbstractRGB` if no one beats me to it.

**Comment by timholy** [comment]
I hope I implemented everything you'll need. Let me know if you have trouble.

**Comment by twadleigh** [comment]
Thanks for doing this. My project for which this would be helpful has been tabled for a while, but I might be getting back around to it soon.
