### ISSUE TITLE
Cannot save (imwrite) Gray image [ERROR: no encode delegate for this image format `MIFF']

### ISSUE THREAD

**Issue by xximranxx** [timholy/Images.jl#240]
Hi,

I am reading in the attached image (its Gray, but missing IMcs info).
![64](https://cloud.githubusercontent.com/assets/6705600/5579923/49faf260-9042-11e4-8966-843a8511343c.jpg)

When I try to imwrite the same image, I get the following error:
ERROR: no encode delegate for this image format `MIFF' @ error/constitute.c/WriteImage/1167
 in error at error.jl:21
 in error at /Users/imran/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:150
 in writeimage at /Users/imran/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:240
 in imwrite at /Users/imran/.julia/v0.3/Images/src/io.jl:164

I use the following code:
img = imread("64.jpg")
imwrite(img,"t.jpg")

Thanks for your help,
Imran

**Comment by timholy** [comment]
I added a link to your wiki page from the README. Since the main issue seems resolved for the purposes of Images proper, I'm closing this, but fee free to reopen if you disagree.
