### ISSUE TITLE
InexactError() when using sc

### ISSUE THREAD

**Issue by pablocouto** [timholy/Images.jl#245]
I’m having some issues using `sc`. If I call `sc(img, 0, 0)` I get an `InexactError()`. This appears to occur whenever its second and third arguments are equal. I tried this with `img` of types `Array{Gray{Ufixed8}}` and `Array{Float32}`.

Following this definition of `sc` in `map.jl`,
```julia
sc(img::AbstractArray, mn::Real, mx::Real) = map(ScaleMinMax(Ufixed8, img, mn, mx), img)
```
I tried `map(ScaleMinMax(Float32, img, 0, 0), img)` and found that this way it works.

I don’t know whether this discrepancy between `ScaleMinMax` and `sc` might be a bug, or just me doing something the wrong way.

**Comment by lucasb-eyer** [comment]
Having these two values equal to eachother results in a division by zero (their difference), which leads to  either `Infinity` or `NaN`, which leads to an `InexactError` when converted to a non-floating-point type. But I don't know why you still get the error with `Float32` and not when calling `map` manually.

**Comment by timholy** [comment]
There's no discrepancy: in one case you're asking for `Float32` outputs (and `Float32` has `Inf` and `NaN`), and in the other case you're asking for `Ufixed8` outputs (which does not).

I've fixed this by making it an error to try to construct a `ScaleMinMax` where the min is equal to the max.
