### ISSUE TITLE
Strange error in OS X reader

### ISSUE THREAD

**Issue by rsrock** [timholy/Images.jl#247]
I'm seeing a strange error here.

```julia
julia> using Images

julia> img = imread(kymograph_image)
ERROR: _var5 not defined
 in imread at /Users/rrock/.julia/v0.3/Images/src/ioformats/OSXnative.jl:60
 in imread at /Users/rrock/.julia/v0.3/Images/src/io.jl:106
```

Anyone recognize `_var5`?  It's not used at the listed line in `OSXnative.jl`.

The ImageMagick reader works for this file:

```julia
julia> img = imread(kymograph_image)
RGB Image with:
  data: 503x1000 Array{RGB{UfixedBase{Uint8,8}},2}
  properties:
    IMcs: sRGB
    spatialorder:  x y
    pixelspacing:  1 1
```

**Comment by timholy** [comment]
That is weird. To me that looks like something generated by the compiler. In a julia session where you've gotten that error (it might change to `_var7` or something else, so best to do it in the same session), what does `@code_typed` show for that function?

**Comment by rsrock** [comment]
Here's a reproducible example from the test suite:

```julia
julia> using Images
julia> const writedir = joinpath(tempdir(), "Images")
julia> abig = Images.colorim(rand(Uint8, 3, 1021, 1026))
RGB Image with:
  data: 1021x1026 Array{RGB{UfixedBase{Uint8,8}},2}
  properties:
    spatialorder:  x y

julia> fn = joinpath(writedir, "big.png")
"/var/folders/2d/ls4zcgc523q37zzjppm8k9gw0000gn/T/Images/big.png"

julia> open(fn, "w") do file
           writemime(file, MIME("image/png"), abig, maxpixels=10^6)
       end
669786

julia> b = Images.imread(fn)
ERROR: _var5 not defined
 in imread at /Users/rrock/.julia/v0.3/Images/src/ioformats/OSXnative.jl:60
 in imread at /Users/rrock/.julia/v0.3/Images/src/io.jl:106
```

Println debugging narrowed down the problem to line 78 of `OSXnative.jl`, not line 60.  Here's where I think the problem lies:

`fillcolor!(reinterpret(T, buf, tuple(4, sz...)), imgsrc, storagedepth)`

`@code_typed` didn't emit anything useful here.  Perhaps an issue with `reinterpret`?

**Comment by timholy** [comment]
Maybe try `@code_typed imread(fn, Images.OSXNative)`? The output will be very long, but if this is correct you should be able to vaguely recognize it as the function in `OSXnative.jl`. `@code_lowered` might be just as useful as `@code_typed`, and will be slightly less verbose.

If you can't make sense of it, it's worth filing a julia issue (include versioninfo as well).

**Comment by rsrock** [comment]
I was just about to post this:

```julia
julia> @code_typed Images.imread(fn, Images.OSXNative)
1-element Array{Any,1}:
 :($(Expr(:lambda, {:filename,symbol("#s148")}, {{},{{:filename,ASCIIString,0},{symbol("#s148"),Type{OSXNative},0}},{}}, :(begin  # /Users/rrock/.julia/v0.3/Images/src/io.jl, line 220:
        return ((top(getfield))(LibOSXNative,:imread))(filename::ASCIIString)
    end))))
```

... but then I discovered that f176e15 fixed this issue.  Tim, you're a wizard!

I have to admit, though, that I don't understand why changing that call from `foo(bar, T)` to `foo{T}(bar, ::Type{T})` fixed the issue (or the first resulted in a bug, after all this time).  In the first method, `T` can be anything, which is probably a bad idea.  However, all of the actual calls to `CFDataGetBytePtr` had types as the second argument.  Why did type inference fail here?

**Comment by timholy** [comment]
Good to hear about the fix; I confess that was entirely accidental, it merely happened as a byproduct of an explicit failure in julia 0.4, which I was able to fix because 0.4 was catching a bug earlier and more accurately.

I suspect that the reason is that a `ccall` is not quite like a typical function call, it's in the direction of a macro or stagedfunction. For example, you can't pass an argument-type-tuple to a function that then uses this in generating a `ccall`---`ccall` needs a tuple-type expression. So I think it was confused by the distinction `T::Type` (where `T` is a _value_ which it knows is some kind of type) but not `::Type{T}` (where `T` is a specific concrete type). I'm not 100% solid on the details of this, though.

**Comment by timholy** [comment]
Oh, also, just for reading `@code_typed` and friends, perhaps you can tell that I screwed up in my advice again: that function was just a stub for calling `Images.OSXNative.imread(filename)`. I should have said `@code_typed Images.OSXNative.imread(filename)`; you'll see the output is just a wee bit longer :smile:.

**Comment by rsrock** [comment]
Would you mind if I go ahead and tag a new version?  I just had a student run into this.  I can take care of it this evening.

Thanks for setting up the dual machine Travis testing, by the way!

**Comment by timholy** [comment]
Please do, sorry I forgot to do it.
