### ISSUE TITLE
Making an image from an RGBA{GLfloat} array causes an error

### ISSUE THREAD

**Issue by ikirill** [timholy/Images.jl#253]
I have some code that looks like this:

    data = Array(RGBA{GLfloat}, (width, height))
    glReadPixels(0, 0, width, height, GL_RGBA, GL_FLOAT, data)
    data = transpose(data)
    ## Images.jl and OpenGL have them upside-down
    img = convert(Image, data[end:-1:1, :])
    @show img
    filename = "last_frame.png"
    imwrite(img, filename)
    @printf "%s\n" "Image written to $filename"

which works absolute fine when I use RGB{GLfloat} and RGB, but if I want to save an RGBA image, I get the following error:

    img => RGBA Image with:
      data: 1024x1024 Array{AlphaColorValue{RGB{Float32},Float32},2}
      properties:
        timedim: 0
        spatialorder:  y x
        pixelspacing:  1.0 1.0
    ERROR: `map` has no method matching   map(::Clamp{AlphaColorValue{BGR{UfixedBase{Uint8,8}},UfixedBase{Uint8,8}}}, ::AlphaColorValue{RGB{Float32},Float32})
     in map! at /XXX/.julia/v0.3/Images/src/map.jl:346
     in image2wand at /XXX/.julia/v0.3/Images/src/io.jl:307
     in imwrite at /XXX/.julia/v0.3/Images/src/io.jl:164
     in save_frame at /XXX.jl:307
     in main_go at /XXX.jl:446
     in main at /XXX.jl:456

Are RGBA images not supported?

**Comment by timholy** [comment]
They're definitely supported, it's just that among the bazillions of [conversion methods](https://github.com/timholy/Images.jl/blob/master/src/map.jl) there are, inevitably, still going to be some missing ones. Should be fixed now, but you'll have to do `Pkg.checkout("Images")` until I tag another release. (I'll check for other unfixed bugs, too, before I do that.)

**Comment by timholy** [comment]
Oh, BTW, you should write your code above something like this:
```julia
data = Array(RGBA{GLfloat}, (width, height))
glReadPixels(0, 0, width, height, GL_RGBA, GL_FLOAT, data)
img = Image(data, spatialorder=["x","y"])
```
No need to call transpose. (It's one of the main design criteria of Images: work with "any" data format as-is.)

**Comment by ikirill** [comment]
> Oh, BTW, you should write your code above something like this:

Thanks very much, that's much better than what I had.

**Comment by ikirill** [comment]
> No need to call transpose. (It's one of the main design criteria of Images: work with "any" data format as-is.)

Actually, `data[:,end:-1:1]` gives the non-upside-down image, not `data`. OpenGL puts the origin at the bottom left pixel, so I guess that's a different convention.

**Comment by timholy** [comment]
Presumably upside down is only meaningful when viewing? If so, ImageView supports lazy-flipping. This is very handy when your image is an entire movie, and you don't want to pay the price of flipping a huge 3d array.
