### ISSUE TITLE
Unknown readremote.jl behaviour

### ISSUE THREAD

**Issue by spiaocet** [timholy/Images.jl#262]
Hey all,

I'm brand new on Julia, and I'm trying to get used to it's image processing packages due to an application I'm supposed to develop. So. I follow the steps mentioned in the "Images" description and once I run 'readremote.jl' it gives me the log below:

![log](https://cloud.githubusercontent.com/assets/11296667/6465390/9a429d0c-c19f-11e4-9b33-8a8ef6b35dbe.png)

I tried to figure out what may be the cause of that, but couldn't find an answer. Having said that the images are not being downloaded to any place of my C: drive, I'd like to know if anyone have a clue of how to manage this issue.

Thanks in advance.

**Comment by timholy** [comment]
I don't think there's anything wrong; those messages are normally printed during the running of those tests. (The "Warning: redefining..." have been eliminated in the most recent, not-yet-released version.) But none of that is an error. Now in your temporary directory (I'm not sure where that is on Windows), you should have the images it fetched.

Another source of images is [TestImages.jl](https://github.com/timholy/TestImages.jl).

**Comment by spiaocet** [comment]
Absolutelly correct. I was able to download them via readremote.jl. Just had to double check the correct path. Thank you.
