### ISSUE TITLE
magnitude inappropriately calls hypot

### ISSUE THREAD

**Issue by cfusting** [timholy/Images.jl#263]
Does not appear this should have ever worked:
```julia
function hypot{T<:FloatingPoint}(x::T, y::T)
```
For example:
```julia
blur = imfilter_gaussian(twob, [50,50])
gx, gy = imgradients(blur)
magnitude(gx, gy)
```
>`hypot` has no method matching hypot(::Image{RGB{Float64},2,Array{RGB{Float64},2}}, ::Image{RGB{Float64},2,Array{RGB{Float64},2}})
while loading In[74], in expression starting on line 3 
>in magnitude at /home/juser/.julia/v0.3/Images/src/edge.jl:95

**Comment by kmsquire** [comment]
Hi Chris, I think I wrote this code before the switch to Images being represented by Colors (or at least only tested it on images with real values).  Should be an easy fix, though.

**Comment by cfusting** [comment]
I think "orientation" has a similar problem calling atan2.

Thanks for looking into it!

**Comment by kmsquire** [comment]
Thanks--I'll look at that too, then.

**Comment by kmsquire** [comment]
Okay, it seems that `hypot` and `atan2` were accidentally changed from two parameters to one in c8e525c8.  Something seems to be wrong with tests as well, as this should have been picked up.

Anyway, I should have a fix shortly.

**Comment by timholy** [comment]
Apologies, @kmsquire. I hope I didn't merge with some old code that then overwrote newer stuff.

**Comment by kmsquire** [comment]
No worries, Tim!  I think #264 should fix this, although I haven't tested it thoroughly yet (in particular, I've only tested on gray scale images so far.)

**Comment by kmsquire** [comment]
Okay, I think #264 is about ready.  Unless I hear differently from @timholy, I'll merge after testing completes.

**Comment by kmsquire** [comment]
@cfusting, this is fixed in the latest master.  You can either do `Pkg.checkout("Images")` or wait until a new version is tagged.

(@timholy, shall I tag a new version?)

**Comment by timholy** [comment]
A new version would be great. Thanks for fixing!

**Comment by kmsquire** [comment]
Done!  @cfusting, `Pkg.update()` should get you the fixed version.
