### ISSUE TITLE
Break due to new changes in v0.4

### ISSUE THREAD

**Issue by joa-quim** [timholy/Images.jl#268]
Not sure if the new changes in 0.4 are really the culprit but I'm getting

`using images
...
Warning: New definition
    trunc(Type{T<:Integer},AbstractArray{G<:Images.ColorTypes.Gray{T<:Union(FloatingPoint,FixedPointNumbers.FixedPoint)},N}) at C:\j\.julia\v0.4\images\src\colortypes.jl:249
is ambiguous with:
    trunc(Type{T},Base.SparseMatrix.SparseMatrixCSC{Tv,Ti}) at sparse/sparsematrix.jl:498.
To fix, define
    trunc(Type{T<:Integer},Base.SparseMatrix.SparseMatrixCSC{_<:Images.ColorTypes.Gray{T<:Union(FloatingPoint,FixedPointNumbers.FixedPoint)},Ti})
before the new definition.
...
Warning: requiring "images" did not define a corresponding module.`

**Comment by timholy** [comment]
This should be fixed by c0f69bcabac42400cbe99b964a9149d53be7abd8 if you do Pkg.update().
