### ISSUE TITLE
nrrd pixel type problems with ITK

### ISSUE THREAD

**Issue by cbecker** [timholy/Images.jl#272]
Images.jl saves the pixel type as something like `ufixedbase{uint8,8}` which confuses ITK.
For example, trying to read a nrrd file after saving it with Images.jl gives me the following error
```
terminate called after throwing an instance of 'itk::ExceptionObject'
itk::ERROR: NrrdImageIO(0x31beb60): ReadImageInformation: Error reading raw.nrrd:
[nrrd] nrrdLoad: trouble reading "raw.nrrd"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: trouble parsing type info |ufixedbase{uint8,8}|
[nrrd] _nrrdReadNrrdParse_type: couldn't parse type "ufixedbase{uint8,8}"
```

Is there a way to save the type as plain uint8?

**Comment by timholy** [comment]
I hate to do this to you, but I'm going to have to ask you to try to fix some of these yourself. I'm not being lazy; today I fixed segfaults, errors, or deprecation warnings in Tk.jl, Cairo.jl, ImageView.jl, Zlib.jl, Zipfile.jl, Winston.jl, and HDF5.jl. It filled my whole day from 4am onward, and I'm a bit tired of it. I can try to keep the packages running as they are, but it's going to take community involvement to make them better.

**Comment by timholy** [comment]
We need a much more comprehensive test suite for NRRD. In particular, it would be interesting to know if unu can read the files we write (it's never been tested).

**Comment by cbecker** [comment]
Hi Tim, I understand the hassle, I am actually working on this one. I hope to have it fixed soon.
Thanks again for your hard work on Images.jl.

Actually nrrd is where I really like Images.jl, as it has native julia support which is great, especially because it doesn't depend on other libraries. It is tricky to catch this errors, as they occur when reading with another software package. I think it broke when the fixed point interpretations where added.

**Comment by cbecker** [comment]
Hi Tim, here there is a fix that deals with `UfixedBase` types.

**Comment by cbecker** [comment]
Closing this as the PR is already in.
