### ISSUE TITLE
MemoryError() when writing pixel value

### ISSUE THREAD

**Issue by cbecker** [timholy/Images.jl#273]
Hello, I am getting a very weird error I haven't seen before,
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.8-pre+2 (2015-03-25 14:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit af187c5* (8 days old release-0.3)
|__/                   |  x86_64-unknown-linux-gnu

julia> using Images

julia> im=imread("posweights.nrrd");

julia> im[1,1,1] = 10
ERROR: MemoryError()
 in setindex! at /home/cjb/.julia/v0.3/Images/src/core.jl:295

julia> im
Gray Image with:
  data: 749x617x308 Array{Float32,3}
  properties:
    colorspace: Gray
    space: left-posterior-superior
    spatialorder:  x y z
    spacedirections:  [1.0,0.0,0.0] [0.0,1.0,0.0] [0.0,0.0,1.0]
    comments:  Complete NRRD file format specification at: http://teem.sourceforge.net/nrrd/format.html
    pixelspacing:  1.0 1.0 1.0
```

I am not sure how to proceed to debug it further, it is a common float32 nrrd file.
Let me know if I can run other diagnostics to help find out what is going on.

**Comment by cbecker** [comment]
This seems to be because Images is memory mapping the contents because `prod(size(im)) > 10^8`, as from https://github.com/timholy/Images.jl/blob/master/src/ioformats/nrrd.jl#L126 , which is actually amazing since I didn't know it was already doing so.

There are a few improvements that could help handling mmaped arrays
  * Add an option like `force_mmap` to `imread()`, which would force memory mapping, if available
  * Add a field in the `Image` type to indicate that the data may be read-only
  * I don't know how to fix this, but julia showing `MemoryError` when trying to write to an array elemen tis not very descriptive, but this is beyond `Images.jl`

The first two seem easy to implement and I can take care of them, let me know if you agree or if you see potential issues.

**Comment by timholy** [comment]
If one wants to change values, the file will need to be opened with read/write permissions. Note that with `mmap`, `A[i,j,k] = v` will *change the data on disk*.

**Comment by cbecker** [comment]
yes, I agree.

But I wouldn't count on opening the file as RW, but instead to let the user know that the image is read-only so that he/she is aware of it.

**Comment by timholy** [comment]
Yes, good idea about improving the error message---I'll see if I can do that (it will be julia 0.4-only). Some of these aren't entirely straightforward because you can't just have `setindex!` return the message you want---it makes the function less optimal for inlining---so you have to intercept an error thrown by the operating system at the point where you are returning messages to the user in the REPL.

You're also right about the keyword. I'm not a 100% certain what the default should be: on by default, off by default, on by default just for large images. Perhaps the options `mmap=true`, `mmap=false`, or `mmap=:auto` would suffice? With the default `:auto`? (what it's doing now)

**Comment by cbecker** [comment]
I agree with having a `mmap` option with `true`, `false` and `:auto` as options.

What needs to be defined is what we do when the reader for a particular type doesn't support `mmap` (eg, ImageMagick-based readers I believe). Shall we throw an error if `mmap=true` is passed?

This means adding the `mmap` option to all readers (plus the base `imread()`) to handle this properly. Does this sound fine to you?
Ideally this should not break existing code, as the default would be `:auto`.

**Comment by cbecker** [comment]
@timholy here there is a PR.

Unfortunately `Pkg.test("Images")` doesn't work so I cannot test if everything is going well. The test also fails with the current upstream master branch of Images.jl

**Comment by timholy** [comment]
Hm, it should work. Travis passed on #278, for example. What test failed for you?

**Comment by cbecker** [comment]
This is the error
```
julia> Pkg.test("Images")
INFO: Testing Images
ERROR: test failed: C[1] == c[1]
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/cjb/.julia/v0.3/Images/test/io.jl, in expression starting on line 91
while loading /home/cjb/.julia/v0.3/Images/test/runtests.jl, in expression starting on line 7
```

and if I add a `@show C[1],c[1]` I get
```
julia> Pkg.test("Images")
INFO: Testing Images
(C[1],c[1]) => (BGRA{Ufixed12}(8.5353,4.2676,2.1338,15.0623),BGRA{Ufixed8}(0.533,0.267,0.133,0.941))
ERROR: test failed: C[1] == c[1]
```

**Comment by timholy** [comment]
Thanks for clarifying. On the latest master that test is disabled (b97492c2bea1ffa535a8294b476e3b1589405cf0). It seems different versions of ImageMagick behave differently.

**Comment by cbecker** [comment]
I see, thanks, I just have to pull then.
