### ISSUE TITLE
Improved doc formatting

### ISSUE THREAD

**Issue by rsrock** [timholy/Images.jl#277]
@timholy Check this out-- it uses dcjones Judo.jl

http://rsrock.github.io/Images.jl

What do you think?

**Comment by kmsquire** [comment]
:+1: !

**Comment by timholy** [comment]
Looks very nice! I think this is almost certainly worth doing. I've not dug into Judo, so let me lay out my vision for documentation and see how it meshes with yours:
- Put the [function reference](https://github.com/timholy/Images.jl/blob/master/doc/function_reference.md) into a bunch of `@doc` calls, so they become accessible from the REPL as `?imfilter`. We could do this now using Docile, but I'm a bit worried about making the loading time even worse than it is now, so I haven't pulled the trigger on this yet.
- Make `?Images` produce some kind of useful summary. On 0.4, if there is no specific help provided for a module, it just spits out the `README.md`.

I had interpreted the second as a reason to keep a nice `README.md`, but now you've got me thinking that there are really two different kinds of overviews, a tutorial and an API summary. I think these have very different purposes: the tutorial is what people should see when they visit the Images.jl page, and the API summary is probably what they should get from `?Images`.

So I think I'm all in favor of the Judo-ification of the current README.

**Comment by rsrock** [comment]
I've updated this, with a few important changes.  Each function in the function reference now has a heading, which allows us to search for functions in the right hand search bar.  Also, we now have dynamic resizing of example images (resize your browser window while looking at the mandrill image on `index.html`).  I also added a simple `makedocs` script, which currently lives in the top level of the Images directory. I plan to commit that into the `gh-pages` branch. Future doc updates should be as simple as merging `master` into `gh-pages`, running `makedocs` from the `Images` folder, and pushing `gh-pages` to github.

I agree with using `@doc`, but also agree that maybe that should come later.  Fortunately, most of what we have here in the Function Reference could migrate there. At some point, Judo may add the ability to add the website function reference from the source code `@doc` macros.

I pulled the intro that's in `index.html` from `README.md`, but there's no reason that we have to keep it that way.  The contents of these two files can diverge from here.

If everyone agrees, I'd like to go ahead and set this up on the main repository. Let me know what you think.

**Comment by timholy** [comment]
I'm in favor!

**Comment by rsrock** [comment]
Ok, it's live.

At some point, we need to put a snazzy image up on the top of the landing page.

**Comment by timholy** [comment]
That is really awesome. Thanks!
