### ISSUE TITLE
Warning in Julia 0.4

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#281]
```julia
using Images
```
>Warning: New definition 
    convert(Type{Images.Image{Cdest<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}}},Images.AbstractImageDirect{Csrc<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N}) at /home/julio/.julia/v0.4/Images/src/core.jl:228
is ambiguous with: 
    convert(Type{Images.Image{T,N,A<:AbstractArray{T,N}}},Images.Image{T,N,A<:AbstractArray{T,N}}) at /home/julio/.julia/v0.4/Images/src/core.jl:202.
To fix, define 
    convert(Type{Images.Image{_<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}}},Images.Image{_<:Union(Color.AbstractAlphaColorValue{C<:Color.ColorValue{T},T<:Real},Color.ColorValue{T}),N,A<:AbstractArray{T,N}})
before the new definition.

**Comment by timholy** [comment]
That's been there forever, and as far as I can tell it seems to be a bug in julia rather than something that Images can do something about.

**Comment by juliohm** [comment]
Hi Tim, should I open an issue in Julia regarding this warning?

**Comment by timholy** [comment]
There are already many such issues; I think Jeff is hoping to tackle such issues once he can do the type system overhaul, https://github.com/JuliaLang/julia/issues/8974.

**Comment by juliohm** [comment]
That is great! Thanks.

**Comment by timholy** [comment]
Fixed in 019525ebf843e47956aa96e3aeed3116c6edff04
