### ISSUE TITLE
Images with IJulia and math

### ISSUE THREAD

**Issue by Jakki42** [timholy/Images.jl#285]
Hi again :) The 16-bit files display on IJulia now fine - thank you!

Still having trouble with IJulia & Images and FixedPointNumbers. (Julia 0.3.7, Windows 8.1, IPython/IJulia 3).

```Julia
Gray Image with:
  data: 512x512 Array{Gray{UfixedBase{Uint16,16}},2}
  properties:
    IMcs: Gray
    spatialorder:  x y
    pixelspacing:  1 1
```
That displays properly.

A simple multiply by 10 makes it (as the FixedPointNumbers doc warns) different:

```Julia
Gray Image with:
  data: 512x512 Array{Gray{Float64},2}
  properties:
    IMcs: Gray
    spatialorder:  x y
    pixelspacing:  1 1
```
And this no longer displays on IJulia, though it does on regular Julia - this is the error:

```Julia
`mapinfo` has no method matching mapinfo(::Type{Gray{UfixedBase{Uint8,8}}}, ::Image{Gray{Float64},2,Array{Gray{Float64},2}})

 in base64 at base64.jl:125
 in display_dict at C:\Users\Jakki\.julia\v0.3\IJulia\src\execute_request.jl:31
```

I also wonder if there is a neat and simple way to  use convert() to turn the Gray{Float64} array of an image into Fixed point array without possibly having to code a needlessly complex function to do it or even having to create a whole new image just to do this?

**Comment by elsuizo** [comment]
Hi your problem is display a Gray image in IJulia?¿
you could silence the output and use PyPlot.imshow function . As follow:
![gray_image_ijulia_2](https://cloud.githubusercontent.com/assets/3966561/7255479/f5571834-e81f-11e4-8ee4-794436a18fe9.png)

**Comment by timholy** [comment]
@Jakki42, Image's `map`/`MapInfo` functionality is basically "`convert` on steroids": you specify the type of transformation you want to achieve with a small type, and then this transformation can be done lazily. I use it all the time when looking at images that are > 1TB in size, to ensure that conversions only happen on the tiny chunk I happen to be looking.

In my limited Julia time, I'm busy with other things, trying to get some (for me) very challenging changes into julia before the 0.4 window closes (https://github.com/JuliaLang/julia/pull/10911). If you want to try fixing this problem yourself, it's probably a few-line change: you basically need to provide a good default `MapInfo` object for the types involved. Hopefully the [documentation](https://github.com/timholy/Images.jl/blob/master/doc/function_reference.md#element-transformation-and-intensity-scaling), and the code in `src/map.jl`, should help.

**Comment by Jakki42** [comment]
@timholy - I had a peek at the code and quickly noticed it's **way** beyond my skill level as a novice Julia programmer to do anything at all to the relevant code :( To make things even worse, it's hard for me to even figure out how to use Git and Julia in this context.

Here are a couple of related problems with tiff-files converted with 'dcraw -D -4 -T':

```Julia
show(x)

Gray Image with:
  data: 6024x4024 Array{Gray{UfixedBase{Uint16,16}},2}
  properties:
    IMcs: Gray
    spatialorder:  x y
    pixelspacing:  1 1

x

`_map` has no method matching _map(::Type{UfixedBase{Uint8,8}}, ::Type{BS{8}}, ::Float64)

 in _map_a! at C:\Users\Jakki\.julia\v0.3\Images\src\map.jl:361
 in map! at C:\Users\Jakki\.julia\v0.3\Images\src\map.jl:353
 in image2wand at C:\Users\Jakki\.julia\v0.3\Images\src\io.jl:332
 in writemime at C:\Users\Jakki\.julia\v0.3\Images\src\io.jl:229
 in base64 at base64.jl:125
 in display_dict at C:\Users\Jakki\.julia\v0.3\IJulia\src\execute_request.jl:31

x*1.0

`mapinfo` has no method matching mapinfo(::Type{Gray{UfixedBase{Uint8,8}}}, ::Image{Gray{Float64},2,Array{Gray{Float64},2}})

 in base64 at base64.jl:125
 in display_dict at C:\Users\Jakki\.julia\v0.3\IJulia\src\execute_request.jl:31

```
the view() function luckily works fine in each case and I'll be using it regardless so the IJulia issues are secondary for me.

@elsuizo - thank you for the hint. I'll keep that in mind if I need to work around the problem(s).

**Comment by timholy** [comment]
OK, this is fixed (all except your `x` example in the post above, which is the same as #269---only happens on big images in IJulia). Also, worth mentioning that @cbecker contributed `raw(img)` which extracts the raw machine representation of the image data.
