### ISSUE TITLE
Finding SVD for the matrix data image 

### ISSUE THREAD

**Issue by simplyman1** [timholy/Images.jl#286]
I want to compute an SVD for the data matrix using built-in function. Also, how to plot SVD in log-scale.

**Comment by lucasb-eyer** [comment]
Please, either read the docs first, or be more specific with your question. [SVD](http://docs.julialang.org/en/release-0.1/stdlib/linalg) is covered in Julia's manual, and there's a whole page about [plotting](http://julialang.org/downloads/plotting.html) right on the downloads page. Getting the data matrix of an image is also one of the first things described in Images.jl's README.md file.

I'm closing this as it's not an issue, but you can re-open it if you have an actual, Images.jl-specific issue.
