### ISSUE TITLE
Image won't read in IJulia

### ISSUE THREAD

**Issue by Humanbird** [timholy/Images.jl#291]
Hi, 
I am trying to read an image with IJulia (I'm using julia 0.3.7 with a mac OSX 10.7.5 lion). Here is what I typed:
using Homebrew
using Images
using ImageView
im=imread("myimage.png")

This is what I get:
error compiling CGImageSourceCreateWithURL: could not load module : dlopen(.dylib, 1): image not found

Any idea of what is going on?

**Comment by rsrock** [comment]
That's a funny one-- the error is telling you that Julia can't find a standard Mac framework, one that should be there on all systems (even back to 10.7, that shouldn't be the problem).

Could you tell me what you get when you run the following lines?  You should see the same path string returned, if all is well.

if you don't have `Compat`, run `Pkg.add("Compat")` first.

```
using Compat
Libdl.find_library(["/System/Library/Frameworks/Foundation.framework/Resources/BridgeSupport/Foundation"])
Libdl.find_library(["/System/Library/Frameworks/ImageIO.framework/ImageIO"])
```

**Comment by Humanbird** [comment]
Thanks for the quick answer rsrock,

For the first command, I get :
"/System/Library/Frameworks/Foundation.framework/Resources/BridgeSupport/Foundation"

For the second one, I get :
""

**Comment by rsrock** [comment]
That's not a good sign.  What do you get when you run this in a terminal window?

```
ls -l /System/Library/Frameworks/ImageIO.framework
```

**Comment by Humanbird** [comment]
No such file or directory

**Comment by rsrock** [comment]
Yeah, that's the problem.  I'm afraid I have some bad news for you. You're missing the ImageIO framework, which was introduced back in OS X 10.4.  I've never seen anything like that before.  There's no telling why that happened, and there's also no telling what else is missing.  I would reinstall the OS if I were you.  Fortunately, you should be able to do an in-place reinstall, so you won't need to restore all of your user's data files.  Nevertheless, **backup**, and verify that backup is good before you start.  

(I have a horror story from a year ago where I did an erase-and-reinstall, and my backup drive died *after* the last backup before the procedure, but *before* I could restore it on my machine.  Luckily, I could recover *almost* everything from a second, older backup).

**Comment by timholy** [comment]
It seems there's nothing for Images.jl to do here, so I'll close it. @Humanbird, you can comment out the OSX reader [here](https://github.com/timholy/Images.jl/blob/b6c833885190c8cc923e5a64b073a0c5ec3ddc7c/src/io.jl#L123-L132).
