### ISSUE TITLE
Can not save image

### ISSUE THREAD

**Issue by Keno** [timholy/Images.jl#294]
I'm trying to save an Image as PNG, but end up getting an empty error string from libmagickwand. Any ideas how to debug/fix?

**Comment by timholy** [comment]
Which step? In `image2wand` or `writeimage`?

One option is to compare a `Cmd` version, although sometimes that's a certain amount of work to get right, too. 7ba0d6093c093acfc5c1d71fa3cad1ff33bccdfc switched to a `ccall` interface, if that helps you.

**Comment by Keno** [comment]
The error comes from `setimageformat(wand, format)`

**Comment by timholy** [comment]
Do the tests pass for you?

**Comment by timholy** [comment]
If you're on OSX, there are many reports of a busted ImageMagick; you might not notice right away if the OSXnative reader (which doesn't support writing) succeeds in reading image files.

There are some instructions on fixing your ImageMagick here:https://github.com/JuliaLang/Homebrew.jl/wiki/Debugging-Homebrew.jl

**Comment by timholy** [comment]
...and here: https://github.com/timholy/Images.jl/blob/master/doc/install.md

(@rsrock, the latter link didn't seem to make it into your fancy new docs)

**Comment by Keno** [comment]
That seemed to work. My apologies for not reading the docs first!

**Comment by timholy** [comment]
Not a problem!

I hope to try the debugger stuff whenever I finish off my current Sisyphean task.

**Comment by rsrock** [comment]
(Fixed that link, and a few more)
