### ISSUE TITLE
Reading JPEG difference between ImageMagick, OS X and MATLAB

### ISSUE THREAD

**Issue by stemann** [timholy/Images.jl#295]
Hi,

It seems imread may return different results when reading a JPEG file when using:
* Images.jl on OS X (unmodified, using OSXNative)
* Images.jl on OS X using ImageMagick

Any ideas why this might be the case?

Also imread in MATLAB 2014b returns a third (different) result.

**Comment by lucasb-eyer** [comment]
The JPEG standard allows for small differences amongst decoders. If the different results you get are within the [allowed ranges](http://en.wikipedia.org/wiki/JPEG#Required_precision), I guess it's nothing to worry about.

**Comment by timholy** [comment]
@stemann, if you can check whether the differences are on that scale, that would be very useful. If not, it could be a colorspace issue, in particular sRGB vs RGB.

**Comment by stemann** [comment]
@lucasb-eyer Thanks.

@timholy Confirmed. The maximum absolute difference is 1.

**Comment by timholy** [comment]
Great, thanks. And thanks @lucasb-eyer!
