### ISSUE TITLE
 function imwrite()

### ISSUE THREAD

**Issue by simplyman1** [timholy/Images.jl#298]
How would I save the images to file using the function imwrite()

**Comment by lucasb-eyer** [comment]
There's an [example in the documentation](http://timholy.github.io/Images.jl/function_reference.html#imwrite). If there's an issue with it, feel free to reopen with more detailed informations.

**Comment by simplyman1** [comment]
How could I reconstruct the image using k largest singular values, where k
is 5% , 10% , 25%, 35%, 50%, of picture's smaller dimension

**Comment by timholy** [comment]
I'm sorry, but this question is not very specific to images; moreover, I can't do your research for you. You'll have to figure it out yourself; hopefully, any image-specific questions you have will be mostly addressed in the documentation in this package. (Where it's not, I appreciate fixes or reports.)
