### ISSUE TITLE
imwrite error

### ISSUE THREAD

**Issue by andrewadare** [timholy/Images.jl#299]
After a recent `Pkg.update()`, I'm now having trouble writing images:
```
julia> img = testimage("mandrill")
julia> imwrite(img, "mandrill.jpg")
ERROR: image coder signature mismatch `MIFF':    68910 !=      210 @ error/module.c/OpenModule/1324
 in error at error.jl:19
 in error at /Users/adare/.julia/v0.4/Images/src/ioformats/libmagickwand.jl:149
 in writeimage at /Users/adare/.julia/v0.4/Images/src/ioformats/libmagickwand.jl:239
 in imwrite at /Users/adare/.julia/v0.4/Images/src/io.jl:189
```
Here's my setup:
```
julia> versioninfo()
Julia Version 0.4.0-dev+4553
Commit af7a8c2 (2015-04-28 14:27 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
julia>
```
Thanks.

**Comment by timholy** [comment]
I suspect you have a broken ImageMagick. My first step is to see if you're on OSX: check. My second step is to refer you to documentation. #294 has links. Let me know if that works.

**Comment by andrewadare** [comment]
I tried the suggestions linked from #294 without any luck. Then I took aim at my system homebrew. I did `brew rm imagemagick`, then `Pkg.build()`, and that worked. I'm not sure why doing `Pkg.update()` earlier today broke the previously peaceful coexistence between my system's homebrew packages and Julia's. Thanks for the quick reply to point me in the right direction.

**Comment by rsrock** [comment]
This looks like an issue that's solved on master of `bindeps.jl`, but a new version hasn't been tagged yet.

If you're willing to check this all out, you should be able to `Pkg.checkout("BinDeps")`.  Then, if you have a system homebrewed imagemagick, `Pkg.build("Images")` will point its `Images/deps/build.jl` to that.  

If you then `brew unlink imagemagick`, and `Pkg.build("Images")` again, then `Images/deps/build.jl` should point to the Julia homebrewed imagemagick.

Related issues:
staticfloat/homebrew-juliadeps#38 (discusses what `Images/deps/build.jl` should look like)
JuliaLang/BinDeps.jl#299

**Comment by andrewadare** [comment]
Sorry for the slow reply here...just confirming that this is now fixed for me. Thanks!

**Comment by timholy** [comment]
Great, thanks for letting us know.
