### ISSUE TITLE
dilation/erosion transpose the image

### ISSUE THREAD

**Issue by yurytsoy** [timholy/Images.jl#301]
Commands dilate and erode rotate the image counter-clockwise.

Example code:
using Images, ImageView, TestImages
using DataFrames, RDatasets
img = testimage("lena")
view(dilate(img)) # the image is rotated
view(dilate(img')) # ok

**Comment by timholy** [comment]
Sorry for the delay. It just needs a variant of the `dilate` function that wraps the return in an image.

**Comment by timholy** [comment]
Fixed in b6c833885190c8cc923e5a64b073a0c5ec3ddc7c

**Comment by yurytsoy** [comment]
No problems, thanks a lot!
