### ISSUE TITLE
error with img1{Gray} ./ img2{Gray}

### ISSUE THREAD

**Issue by elsuizo** [timholy/Images.jl#303]
```julia
julia> using Images

julia> img1 = imread("/home/elsuizo/Optical_flow/Images/hamburg_tax1.jpg")
Gray Image with:
  data: 442x442 Array{Gray{UfixedBase{Uint8,8}},2}
  properties:
    IMcs: Gray
    spatialorder:  x y
    pixelspacing:  1 1

julia> img2 = imread("/home/elsuizo/Optical_flow/Images/hamburg_tax2.jpg")
Gray Image with:
  data: 442x442 Array{Gray{UfixedBase{Uint8,8}},2}
  properties:
    IMcs: Gray
    spatialorder:  x y
    pixelspacing:  1 1

julia> img1 ./ img2
ERROR: InexactError()
 in _F_ at broadcast.jl:96
 in broadcast! at broadcast.jl:227
 in ./ at /home/elsuizo/.julia/v0.3/Images/src/algorithms.jl:48


```

**Comment by timholy** [comment]
try `float32(img1)./img2` and see if it works

**Comment by elsuizo** [comment]
Yes it works, but my problem is now this:

```julia

    u = u₀ 
    v = v₀
    # compute the derivatives
    f_x,f_y,f_t = images_derivatives(img₁,img₂)
    # compute the average images
    k_av = [1/12 1/6 1/12;1/6 0 1/6;1/12 1/6 1/12]

    #while norm()

    for i in 1:iter

        #compute the local average of the flow vectors
        u_av = imfilter(u,k_av)
        v_av = imfilter(v,k_av)

        P = f_x .* u_av + f_y .* v_av + f_t
        D = α + (f_x).^2 + (f_y).^2

        u = u_av - f_x .* (float32(P) ./ D) #here
        v = v_av - f_y .* (float32(P) ./ D) #here

    end

    return u,v
```
the division `P ./ D` generated this error:
```julia
ERROR: MethodError: `zero` has no method matching zero(::Type{Any})
```
why look at Any type. If all operations preserved the original Gray type?

**Comment by timholy** [comment]
Are you wrapping this in a function? Type inference doesn't usually work at the command line.

**Comment by elsuizo** [comment]
yes the code is inside a function, maybe is wrong the initialization of `u₀` and `v₀` , but a tried `rand()` `zeros()` `ones()` . Or the kernel filters

**Comment by timholy** [comment]
Can you sprinkle `@show typeof(x)` statements in various places to figure out where the type-instability is coming from?

**Comment by elsuizo** [comment]
Hi Tim the problem is whit the `.^` operator. Redefinition lost? I look at the source code and can not find

Notebook test:
https://github.com/elsuizo/Optical_flow/blob/master/Horn_Schunck/tests.ipynb

Thanks for you time 
Regards

**Comment by timholy** [comment]
OK, if you do `Pkg.checkout("Images")` you should be good to go.

**Comment by tlnagy** [comment]
Is there any better solution to this problem when dividing an image by another? Is the only solution to switch to floats? 

When I try doing flat field correction by dividing by the flat field, it's really close to working but due to noise it slips over:

```
ArgumentError: FixedPointNumbers.Normed{UInt16,16} is a 16-bit type representing 65536 values from 0.0 to 1.0; cannot represent 1.0083102
```
