### ISSUE TITLE
RGB{T} scaling/mapping

### ISSUE THREAD

**Issue by Jakki42** [timholy/Images.jl#304]
Seems like ScaleAutoMinMax etc. don't work for images with RGB{T} content, or maybe I just do something wrong.

```Julia
mi = ScaleAutoMinMax(RGB{Ufixed16})
map(mi,test)

`isless` has no method matching isless(::RGB{UfixedBase{Uint16,16}}, ::RGB{UfixedBase{Uint16,16}})
while loading In[94], in expression starting on line 1
```
Using grayscale images or colour images of [x,y,3] ordering works fine.

**Comment by timholy** [comment]
This is a tougher one, because there is no ordering on RGB values. Does one want this to work in each color channel separately, or on the color channel with smallest/largest "raw" value?

**Comment by timholy** [comment]
I decided it should work across color channels, not within color channels.
