### ISSUE TITLE
dilation of boolean arrays

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#311]
```julia
dilate(trues(3))
```
>ERROR: MethodError: `extremefilt!` has no method matching extremefilt!(::BitArray{1}, ::Base.Order.ForwardOrdering, ::Array{Int64,1})
Closest candidates are:
  extremefilt!(::Array{T,N}, ::Base.Order.Ordering, ::Any)
  extremefilt!(::Array{T,N}, ::Base.Order.Ordering)
 in dilate at /home/julio/.julia/v0.4/Images/src/algorithms.jl:1124

I'm trying to dilate some binary images that are actually represented by true/false values.

**Comment by timholy** [comment]
Fixed
