### ISSUE TITLE
Feature Request: imread(::IOBuffer)

### ISSUE THREAD

**Issue by shashi** [timholy/Images.jl#312]
I am getting camera images from the browser in base64 encoded format. I can decode it to a `Array{UInt8,1}` but then to read it in as an image I need to save it and then `imread` the saved file. Or is there another way to do this?

The base64 images are in PNG format, it looked like `LibMagick.readimage(wand, ::IO)`  would do the trick, I converted the `Array{UInt8, 1}` to an IOBuffer, but it looks like `CFILE` call in the `ccall` does not work on a IOBuffer.

How can I go about making this work?

**Comment by timholy** [comment]
If you checkout master, it's just `imread(io, Images.ImageMagick)`. (Sorry, this seemed to have bit-rotted because there wasn't a test.)

**Comment by shashi** [comment]
Awesome! :-)
