### ISSUE TITLE
imfilter() and imfilter_fft() produce different output for large numbers

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#318]
I'm not aware of the implementation details. Is it possible to solve this issue efficiently?

```julia
imfilter([typemax(Int) 1; 1 1], ones(2,2))
```
>2x2 Array{Float64,2}:
 9.22337e18  4.0
 4.0         4.0

```julia
imfilter_fft([typemax(Int) 1; 1 1], ones(2,2))
```
>2x2 Array{Float64,2}:
   9.22337e18    0.0   
 735.471       -52.8045

**Comment by timholy** [comment]
Are you asking whether it's possible to make them give the same output? Not really. You can't even represent `typemax(Int)` as a `Float64` without losing precision, and roundoff error (which is all this is) will always be sensitive to the algorithm used.

**Comment by juliohm** [comment]
Hi Tim, thank you for the clarification, I'm closing the issue.
