### ISSUE TITLE
Error updating on Windows

### ISSUE THREAD

**Issue by joa-quim** [timholy/Images.jl#329]
```LoadError: type Void has no field match
while loading C:\j\.julia\v0.4\Images\deps\build.jl, in expression starting on line 37```

This happens because of the ```>``` char in 

```pattern = ">ImageMagick-6.9.*-Q16-$(OS_ARCH)-dll.exe"```

If remove it, than

```julia> magick_exe = convert(ASCIIString, m.match)```

"ImageMagick-6.9.1-10-Q16-x64-dll.exe"

**Comment by timholy** [comment]
2nd report: https://groups.google.com/d/msg/julia-users/_yeSl2i03LE/YhD51k7bKAAJ.

Issue filed with the ImageMagick developers: http://www.imagemagick.org/discourse-server/viewtopic.php?f=2&t=28184

Let's see what they say, and if no support is forthcoming I'll make this change and tag a new version.

**Comment by joa-quim** [comment]
As I mentioned in the julia-users, removing the [2:end] in `magick_exe = convert(ASCIIString, m.match)[2:end]` is also necessary

**Comment by timholy** [comment]
@tkelman, on that forum I was encouraged to use ftp://ftp.imagemagick.org/pub/ImageMagick/releases. Can we work with any of those files?

**Comment by timholy** [comment]
Or maybe better ftp://ftp.imagemagick.org/pub/ImageMagick/windows/releases/

**Comment by tkelman** [comment]
Those look like source releases? We should probably pick a release every so often and mirror it to bintray or wherever else. Happy to give you access to https://bintray.com/julialang. ref https://github.com/stevengj/Blosc.jl/issues/10#issuecomment-128015245

**Comment by timholy** [comment]
They pointed me here: https://help.github.com/articles/distributing-large-binaries/

But sure, bintray sounds good. What would you suggest?

**Comment by tkelman** [comment]
Github releases has a slightly-fewer-clicks UI to upload files manually than bintray, but I think it doesn't make too much sense to attach files for an upstream project to your own github release. The github releases have to be associated with tags in the repo, I believe.

**Comment by timholy** [comment]
OK, let's do the bintray thing. I'll take that offer for access.

**Comment by tkelman** [comment]
Bintray lets you log in with github auth, I think you need to request permission via the join button at https://bintray.com/julialang
