### ISSUE TITLE
Contrast error

### ISSUE THREAD

**Issue by postoroniy** [timholy/Images.jl#332]
using Images, ImageView
x=ones(100,100)
view(grayim(x))
right click  and choose "Contrast"
after what you run into problem immediately, check log below
"error during Tk callback: 
ERROR: range step cannot be zero
 in colon at ./range.jl:139
 in prepare_histogram at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:181
 in contrastgui at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:85
 in contrastgui at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:28
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/display.jl:312
 in jl_tcl_callback at /home/slava/.julia/v0.3/Tk/src/tkwidget.jl:146
"
That's because slider max or min crossed.
I saw this problem when I adjust contrast by moving sliders min or max.
I couldn't fix it by myself please help or give an advice.

**Comment by rsrock** [comment]
That image won't have any contrast, all pixels are the same value.  That probably baffles the histogram / contrast control.

Try `x = rand(100, 100)`

**Comment by postoroniy** [comment]
ok I gave wrong example sorry, and after x=rand(100,100);view(grayim(x)) I moved min slider to maximum level I got this
error during Tk callback: 
ERROR: min must be smaller than max
 in ScaleMinMax at /home/slava/.julia/v0.3/Images/src/map.jl:175
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/display.jl:310
 in rerender at /home/slava/.julia/v0.3/ImageView/src/display.jl:678
 in redraw at /home/slava/.julia/v0.3/ImageView/src/display.jl:683
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/display.jl:312
 in rerender at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:97
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:156
 in anonymous at /home/slava/.julia/v0.3/Tk/src/widgets.jl:268
 in jl_tcl_callback at /home/slava/.julia/v0.3/Tk/src/tkwidget.jl:146
What I tried to do yesterday it was fixing max min values at contrast.jl at lines 146..169
it didn't help.
BTW I saw the same error on linux and on windows

**Comment by postoroniy** [comment]
ok...looks like fixed. It works for me but it doesn't fix problem when all data in array are equal 
diff --git a/src/contrast.jl b/src/contrast.jl
index 7b3d343..881dc59 100644
--- a/src/contrast.jl
+++ b/src/contrast.jl
@@ -116,7 +116,7 @@ function contrastgui{T}(win::Tk.TTk_Container, img::AbstractArray{T}, cs::Contra
             my_min = float32(get_value(emin))
             my_max = float32(get_value(emax))
             # Don't let values cross
-            my_max = my_max < my_min ? my_min + 0.01f0 : my_max # offset is arbitrary
+            my_max = my_max <= my_min ? my_min + 0.01f0 : my_max # offset is arbitrary
             cs.min = convertsafely(typeof(cs.min), my_min)
             cs.max = convertsafely(typeof(cs.max), my_max)
             set_value(emax, string(my_max)) # caution: each widget gets it's own type
@@ -132,7 +132,7 @@ function contrastgui{T}(win::Tk.TTk_Container, img::AbstractArray{T}, cs::Contra
             my_min = float32(get_value(emin))
             my_max = float32(get_value(emax))
             # Don't let values cross
-            my_min = my_min > my_max ? my_max - 0.01f0 : my_min # offset is arbitrary
+            my_min = my_min >= my_max ? my_max - 0.01f0 : my_min # offset is arbitrary
             cs.min = convertsafely(typeof(cs.min), my_min)
             cs.max = convertsafely(typeof(cs.max), my_max)
             set_value(emin, string(my_min))
@@ -147,7 +147,7 @@ function contrastgui{T}(win::Tk.TTk_Container, img::AbstractArray{T}, cs::Contra
         my_min = float32(min_slider[:value])
         my_max = float32(max_slider[:value])
         # Don't let values cross
-        my_max = my_max < my_min ? my_min + 0.01f0 : my_max # offset is arbitrary
+        my_max = my_max <= my_min ? my_min + 0.01f0 : my_max # offset is arbitrary
         cs.min = convertsafely(typeof(cs.min), my_min)
         cs.max = convertsafely(typeof(cs.max), my_max)
         set_value(emin, string(my_min))
@@ -159,7 +159,7 @@ function contrastgui{T}(win::Tk.TTk_Container, img::AbstractArray{T}, cs::Contra
         my_min = float32(min_slider[:value])
         my_max = float32(max_slider[:value])
         # Don't let values cross
-        my_min = my_min > my_max ? my_max - 0.01f0 : my_min # offset is arbitrary
+        my_min = my_min >= my_max ? my_max - 0.01f0 : my_min # offset is arbitrary
         cs.min = convertsafely(typeof(cs.min), my_min)
         cs.max = convertsafely(typeof(cs.max), my_max)
         set_value(emin, string(my_min))

**Comment by postoroniy** [comment]
above patch is not really fixing
still having these  errors while moving min slider closer to value of  max  slider
error during Tk callback: 
ERROR: min must be smaller than max
 in ScaleMinMax at /home/slava/.julia/v0.3/Images/src/map.jl:175
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/display.jl:310
 in rerender at /home/slava/.julia/v0.3/ImageView/src/display.jl:678
 in redraw at /home/slava/.julia/v0.3/ImageView/src/display.jl:683
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/display.jl:312
 in rerender at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:97
 in anonymous at /home/slava/.julia/v0.3/ImageView/src/contrast.jl:156
 in anonymous at /home/slava/.julia/v0.3/Tk/src/widgets.jl:268
 in jl_tcl_callback at /home/slava/.julia/v0.3/Tk/src/tkwidget.jl:146

**Comment by rsrock** [comment]
Seems like a reasonable fix.  Could you open a pull request over at timholy/ImageView.jl ?

**Comment by timholy** [comment]
@postoroniy, thanks for the patch. If you're unfamiliar with the process of submitting a pull request, it's described [here](http://docs.julialang.org/en/release-0.3/manual/packages/#package-development). But let me know if you'd prefer me to commit it directly.

**Comment by postoroniy** [comment]
I'll put pull request soon, thanks
