### ISSUE TITLE
restrict doesn't copy pixelspacing only the reference

### ISSUE THREAD

**Issue by dolejm1** [timholy/Images.jl#347]
When using restrict, the resulting image shares pixelspacing with the original one.
The new pixelspacing is OK, but pixelspacing of the original image is spoiled this way.

**Comment by timholy** [comment]
Thanks for the report. It's a 1-liner fix, though a test would be nice. Want to contribute the fix yourself (hint: `@which restrict(img, ...)`), or are you asking me?

**Comment by dolejm1** [comment]
I am kindly asking you.

**Comment by timholy** [comment]
OK, fixed if you do `Pkg.update()`.
