### ISSUE TITLE
Slowdown in displaying large images in IJulia

### ISSUE THREAD

**Issue by cstjean** [timholy/Images.jl#351]
I Pkg.updated today for the first time in two weeks, and had to deal with the Color->Colors changes. Displaying large images in IJulia is now much slower than it was. I never timed it before, but now displaying a (1320,2420) image takes > 20 seconds (it gets resized automatically, so maybe the resizing code was changed?) whereas my recollection is that it was basically instantaneous.

I just have this large image in one variable, `im`, whose type is `Image{RGBA{UfixedBase{Uint8,8}},2,Array{RGBA{UfixedBase{Uint8,8}},2}}`. Then entering a cell with just

`im`

takes >20 seconds to display the image on OSX, Julia 3.10. Apologies for the lack of clear comparison - if this does not ring a bell at all, please just close the issue as non-reproducible.

**Comment by lucasb-eyer** [comment]
Did you also update Jupyter/IPython? I recall they turned on image-resizing (possibly using html) by default not too long ago. Still, my browser never took >20s to resize an image, so this is just a wild guess.

**Comment by cstjean** [comment]
No, did not update IJulia/Jupyter recently (unless Pkg.update() caused that). IJulia has always resized images for as long as I've been using Julia (~June), but the slowdown is (with 60% certainty) new to this update. I thought that the resizing was done on the Images.jl side of things and not Jupyter. It's definitely not on the browser side, though, `Right-Click + View Image` does not show the original image.

Incidentally, I just got a strong indication that the resizing is the culprit. I have a (256,233) image, `img`. The code 
`hcat([img for _ in 1:16]...)`
shows the image in < 1 second, whereas 
`hcat([img for _ in 1:17]...)`
takes ~4 seconds. If I get confirmation that resizing is Jupyter's responsibility, then I'll bring it up to them.

**Comment by lucasb-eyer** [comment]
Your investigation sounds reasonable, and I am no further help then, sorry.

**Comment by cstjean** [comment]
More datapoints, all run in IJulia....

```julia
> typeof(im)
Image{RGBA{UfixedBase{Uint8,8}},2,Array{RGBA{UfixedBase{Uint8,8}},2}}

> size(im)
(1320,2100)

# compiler warm-up omitted....

> @time display(im) # My guesstimate of 20 seconds was either wrong, or it was slower yesterday
elapsed time: 13.672699043 seconds (2036806320 bytes allocated, 52.76% gc time)

> @time display(Images.subim(im, 1:1000, 1:1000)) # doesn't trigger resizing
elapsed time: 0.534126051 seconds (44021608 bytes allocated, 32.91% gc time) # 44 MB

> @time display(Images.subim(im, 1:1000, 1:2000)) # triggers resizing
elapsed time: 10.289207356 seconds (1474391548 bytes allocated, 50.26% gc time) # 1.4 GB
```
I also tried changing spatialorder, converting to ARGB or RGB, but none of that had any effect on the running time. My conclusions are:
- Image resizing is definitely performed on the Julia side of things, probably in Images.jl
- That's a slow operation.
- The slowdown may or may not have happened during the last two weeks' worth of commits and changes. I want to say it did, but I don't really know.

I could revert the changes to confirm the last point, but that's messy. I'll dive into Images.jl internals if this becomes too much of an issue. This algorithm shouldn't be that slow. It seems to me that we should let the browser do the resizing (by giving it <img ... width=...> tags) rather than resize in Julia, but there may be good reasons not to do it this way.

**Comment by timholy** [comment]
Can you try profiling? (I'd do it but I am just swamped.) My guess is there's something wrong with `restrict`, which engages when images hold more than a megapixel.

**Comment by cstjean** [comment]
I was just doing that! Two thirds of the run time is on [this line](https://github.com/timholy/Images.jl/blob/a3b178c45968fd7bc1bfaeece0ba9a53ca84037e/src/algorithms.jl#L1008), which looks innocent enough, but it calls slow [addition](https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/master/src/ColorVectorSpace.jl#L100) and [multiplication](https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/master/src/ColorVectorSpace.jl#L81) operations in ColorVectorSpace (line numbers taken from ProfileView - they are off, but I don't know which line is actually called)

![screen shot 2015-09-02 at 10 49 03](https://cloud.githubusercontent.com/assets/8622776/9634557/45237eda-5160-11e5-8060-dbccbe2add01.png)

**Comment by timholy** [comment]
Something is type-unstable. You sometimes get better line numbers if you run `julia --inline=no` (on julia 0.4)

**Comment by cstjean** [comment]
That's what I thought too.
> My guess is there's something wrong with restrict, which engages when images hold more than a megapixel
restrict is not called at all on small images, I just checked, which is why it's not slow. This is on Julia 0.3.10 BTW, don't know if type inference is any better on 0.4.

Thanks for the feedback.

**Comment by cstjean** [comment]
The rest of my code is also slowed down significantly (X2 runtime). It doesn't call `restrict`, but it's ~90% image manipulation, and I see these red boxes pointing to ColorVectorSpace.jl:81 and :100 all over the place. I've tried to build a test case, and this is the shortest I have:

![screen shot 2015-09-02 at 14 13 49](https://cloud.githubusercontent.com/assets/8622776/9639978/eea208f2-517c-11e5-9e69-bb332cf680ba.png)

I assume that the multiplication and setindex! functions should be inlined? They are when I run the same code with `ones(Ufixed8, 10000)`

HTH.

**Comment by timholy** [comment]
Can you say `Pkg.checkout("ColorTypes")` and see if that helps? See https://github.com/JuliaGraphics/ColorTypes.jl/pull/8

**Comment by cstjean** [comment]
```julia
@time display(im)
elapsed time: 9.122000199 seconds (1900075112 bytes allocated, 35.03% gc time)```
![screen shot 2015-09-03 at 09 45 53](https://cloud.githubusercontent.com/assets/8622776/9659842/9904c804-5220-11e5-98a9-16f01cb888d0.png)
I think it has improved some, but it's still allocating in that test. Is that expected?

**Comment by timholy** [comment]
Oh, that's very interesting. Because I don't have your `im`, I tested this way:
```jl
julia> img = colorim(rand(Uint8, 3, 800, 800), "RGB")
RGB Image with:
  data: 800x800 Array{RGB{UfixedBase{Uint8,8}},2}
  properties:
    spatialorder:  x y

# After warmup
julia> @time restrict(img)
elapsed time: 0.018994739 seconds (11560368 bytes allocated)
RGB Image with:
  data: 401x401 Array{RGB{Float64},2}
  properties:
    spatialorder:  x y
    pixelspacing:  2.0 2.0
```
But now I notice your image is `RGBA`, and I get:
```
julia> img = colorim(rand(Uint8, 4, 800, 800), "RGBA")
RGBA Image with:
  data: 800x800 Array{RGBA{UfixedBase{Uint8,8}},2}
  properties:
    spatialorder:  x y

julia> @time restrict(img)
elapsed time: 2.4841731 seconds (461776976 bytes allocated, 34.54% gc time)
RGBA Image with:
  data: 401x401 Array{RGBA{Float64},2}
  properties:
    spatialorder:  x y
    pixelspacing:  2.0 2.0
```
which is obviously borked.

Let's try again: another `Pkg.checkout`, please.

**Comment by cstjean** [comment]
Way better! display took
`elapsed time: 0.245360811 seconds (86390776 bytes allocated, 31.26% gc time)`
and the other test:
![screen shot 2015-09-03 at 10 46 00](https://cloud.githubusercontent.com/assets/8622776/9661510/030d79a0-5229-11e5-9dd5-c2d08aae8ffd.png)
I'm still a bit surprised that `setindex!` and `*` didn't get inlined, but at least it's not allocating anything in the inner loop.

I'll run the rest of my code, but it looks great so far. Thank you! Very appreciated!

**Comment by timholy** [comment]
It's slower than you'd like because multiplication goes through a `FloatingPoint` intermediate and then it has to call `trunc`. That's probably why it's not getting inlined.

**Comment by cstjean** [comment]
That makes sense. Is there a way around this? I'm overlaying one image on top of another, by multiplying the color components by the alpha channel. It is now <5% of runtime, so I don't worry about it, but it seems like unless I were to use `RGBA{Float32}`, the intermediate conversion to Float is unavoidable, short of defining `(*)(Ufixed8, Ufixed8)` myself.

**Comment by timholy** [comment]
Images has an internal method `restrict!` where you can specify the output array. You could pass in an `RGBA{Float32}` so it doesn't convert back. But you have to manage the sizes manually.

I'm open to other suggestions (preferably via a pull request).

**Comment by cstjean** [comment]
I will try to contribute, thank you for your time!

**Comment by timholy** [comment]
You know, perhaps the right way to fix it *is* (as you implied) to make `Ufixed8` closed under multiplication, and do the bit-shifting operations described here: https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/19#issue-64848916. If you decide to tackle this, I'd first check that possibility out and see how you like it.
