### ISSUE TITLE
Crash report on imread of a file

### ISSUE THREAD

**Issue by simsim314** [timholy/Images.jl#354]
Try to imread this file and the crash report follows: 
![20266430458_6043b9498a](https://cloud.githubusercontent.com/assets/5075688/9701189/767a1362-5427-11e5-98ec-33288380218c.jpg)

using Images
img = Images.imread("20266430458_6043b9498a.jpg")

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x7feee5d2bc3 -- log at  (unknown line)
log at C:\Users\SimSim314.julia\v0.3\Images\deps\usr\lib\x64\MSVCR120.dll (unknown line)
DestroyQuantizeInfo at C:\Users\SimSim314.julia\v0.3\Images\deps\usr\lib\x64\CORE_RL_magick_.dll (unknown line)

QuantizeImage at C:\Users\SimSim314.julia\v0.3\Images\deps\usr\lib\x64\CORE_RL_magick_.dll (unknown line)
SetImageType at C:\Users\SimSim314.julia\v0.3\Images\deps\usr\lib\x64\CORE_RL_magick_.dll (unknown line)
getimagetype at C:\Users\SimSim314.julia\v0.3\Images\src\ioformats/libmagickwand.jl:294
imread at C:\Users\SimSim314.julia\v0.3\Images\src\io.jl:269
jlcall___imread#91___3253 at  (unknown line)
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
julia_imread_3252 at  (unknown line)
imread at C:\Users\SimSim314.julia\v0.3\Images\src\io.jl:139
julia_imread_3234 at  (unknown line)
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr_in at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_load_file_string at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
include_string at C:\Users\SimSim314.julia\v0.3\Jewel\src\eval.jl:32
jlcall_include_string_2265 at  (unknown line)
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_f_top_eval at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
include_string at C:\Users\SimSim314.julia\v0.3\Jewel\src\eval.jl:36
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
eval at C:\Users\SimSim314.julia\v0.3\Jewel\src\LightTable\eval.jl:11
evaldisplay at C:\Users\SimSim314.julia\v0.3\Jewel\src\LightTable\eval.jl:22
jlcall___evaldisplay#46___2259 at  (unknown line)
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
julia_evaldisplay_2258 at  (unknown line)
jlcall_evaldisplay_2258 at  (unknown line)
anonymous at C:\Users\SimSim314.julia\v0.3\Jewel\src\LightTable\eval.jl:53
handlecmd at C:\Users\SimSim314.julia\v0.3\Jewel\src\LightTable/LightTable.jl:65
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
handlenext at C:\Users\SimSim314.julia\v0.3\Jewel\src\LightTable/LightTable.jl:81
server at C:\Users\SimSim314.julia\v0.3\Jewel\src\LightTable/LightTable.jl:22
jlcall_server_1709 at  (unknown line)
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_f_apply at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
server at C:\Users\SimSim314.julia\v0.3\Jewel\src\Jewel.jl:15
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_f_apply at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_load_ at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
include at boot.jl:245
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:128
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
process_options at client.jl:285
_start at client.jl:354
jlcall__start_364 at  (unknown line)
jl_apply_generic at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
unknown function (ip: 4200686)
julia_trampoline at C:\Users\SimSim314\Downloads\juno\resources\app\julia\bin\libjulia.dll (unknown line)
unknown function (ip: 4202914)
unknown function (ip: 4199436)
unknown function (ip: 4199739)
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)

**Comment by SimonDanisch** [comment]
I can't reproduce this with:
```Julia
julia> versioninfo()
Julia Version 0.4.0-pre+7133
Commit 0f7dee9 (2015-09-01 22:04 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
and FileIO, which should be in a similar state as the current `Images`.

**Comment by simsim314** [comment]
I currently have an issue with 0.4.0-pre and Images. 

It fails in the release:

julia> versioninfo()
Julia Version 0.3.11
Commit 483dbf5* (2015-07-27 06:18 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by timholy** [comment]
If you still have problems with this image, please let us know. (Works for me on current versions.)
