### ISSUE TITLE
Type-unstable `similar` and `copy`

### ISSUE THREAD

**Issue by cdsousa** [timholy/Images.jl#356]
For example, doing `code_warntype(copy, (Images.Image{Float64,2,Array{Float64,2}},))`, yields an abstract `::Images.Image{T,N,A<:AbstractArray{T,N}}` return type.

This also happens with the `similar` method, and seems to be due to a type-unstable `Image` constructor.

**Comment by cdsousa** [comment]
I've around this and it seems the type-unstability resumes to line https://github.com/timholy/Images.jl/blob/master/src/core.jl#L14 ,
and more concretely to the `ndims` return value which, unlike `eltype` and `typeof`, doesn't allow full type inference of the new `Image` object...

**Comment by cdsousa** [comment]
And this seems to be an upstream issue:

```Julia
type X{T}; end
f(x) = X{ndims(x)}()
code_warntype(f, (Array{Int,2},))
```
returns
```
Variables:
  x::Array{Int64,2}

Body:
  begin  # none, line 1:
      return call((top(apply_type))(Main.X,2)::Type{_<:X{T}})::X{T}
  end::X{T}
```

Does anyone knows if this is something already discussed in Julia list or issues?

**Comment by timholy** [comment]
It's due to this:
```jl
julia> @inferred(deepcopy(img.properties))
ERROR: return type Dict{ASCIIString,Any} does not match inferred return type Any
 in error at ./error.jl:21
```
which is used in Images' copy function. We use it because of this:
```jl
julia> p = Dict{ASCIIString,Any}("Hi" => rand(2,2))
Dict{ASCIIString,Any} with 1 entry:
  "Hi" => 2x2 Array{Float64,2}:…

julia> pointer(p["Hi"])
Ptr{Float64} @0x00007fbccb82b760

julia> pc = copy(p)
Dict{ASCIIString,Any} with 1 entry:
  "Hi" => 2x2 Array{Float64,2}:…

julia> pointer(pc["Hi"])
Ptr{Float64} @0x00007fbccb82b760
```

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/pull/13323

**Comment by cdsousa** [comment]
There may be different causes for the issue at each method. For the `similar` method the problem is in the Image constructor  (https://github.com/timholy/Images.jl/issues/356#issuecomment-139681364) due to the unstability of `ndims`  which suffers from an inference bug already reported: https://github.com/JuliaLang/julia/issues/13082.

There is a workaround for that, and I should have already proposed a PR:
Replacing  line https://github.com/timholy/Images.jl/blob/master/src/core.jl#L14
with
```julia
Image{n}(data::AbstractArray{n}, props::Dict) = Image{eltype(data),n,typeof(data)}(data,props)
```
will fix `similar` method (and probably other methods too).
