### ISSUE TITLE
When to tag new FileIO interface?

### ISSUE THREAD

**Issue by rsrock** [timholy/Images.jl#378]
I'd like to propose that we wait until 0.4 is released, which should be any day now. Or at the very least, update the REQUIRE line to require at least 0.4-rc3 before tagging.  I'm not sure we want to be supporting this on 0.3.

**Comment by timholy** [comment]
I agree it's a good idea to combine two disruptive changes---the FileIO transition and the abandonment of 0.3---into one tag. We don't really have to wait until 0.4 is released, though---we can make it REQUIRE julia 0.4-.

Waiting until the FileIO stuff is solid wrt to QuartzImageIO/ImageMagick is probably the better timing consideration, I'd say.

**Comment by rsrock** [comment]
Looks like this is finished
