### ISSUE TITLE
Restrict's colors are now wrong (saturated?)

### ISSUE THREAD

**Issue by cstjean** [timholy/Images.jl#395]
Resized images have never been this disturbing :)

![screen shot 2015-11-05 at 07 02 27](https://cloud.githubusercontent.com/assets/8622776/10967838/67812b46-838b-11e5-9792-ad0c97824fbb.png)

It coincided with the FixedPointNumbers update from last week (not the latest one). I figured that it would be fixed along with the UFixed multiplication bug, but it persisted. HTH.

**Comment by timholy** [comment]
Huh. That is scary. I'll get to this when I can, but don't expect it to be immediate.

**Comment by cstjean** [comment]
This affects all large images displayed in IJulia. Could we make the `maxpixels` default a global variable so that the `restrict` call is skippable until a fix is available?

```julia
function writemime(io::IO, mime::MIME"image/png", img::AbstractImage; mapi=mapinfo_writemime(img), minpixels=10^4, maxpixels=10^6)
    assert2d(img)
    A = data(img)
    nc = ncolorelem(img)
    npix = length(A)/nc
    while npix > maxpixels
        A = restrict(A, coords_spatial(img))
        npix = length(A)/nc
    end
```

**Comment by cstjean** [comment]
Or - we can replace that `restrict` call with `imresize`. The antialising looks worse, but the colors are OK.

**Comment by cstjean** [comment]
Thank you, much appreciated!
