### ISSUE TITLE
ERROR: LoadError: KeyError: RGBA not found

### ISSUE THREAD

**Issue by yakir12** [timholy/Images.jl#396]
Hi Tim!
I get a KeyError warning and then an error when trying to save an RGBA image:
```julia
using Images
a = rand(10, 10, 4)
img = colorim(a, "RGBA")
save("a.png", img)
```
I tried this with both the tagged and checked-out versions of `Images.jl`. 
Here's the output: 
```julia
WARNING: KeyError("RGBA")
 in setimagecolorspace at /home/yakir/.julia/v0.4/ImageMagick/src/libmagickwand.jl:309
 in constituteimage at /home/yakir/.julia/v0.4/ImageMagick/src/libmagickwand.jl:196
 in image2wand at /home/yakir/.julia/v0.4/ImageMagick/src/ImageMagick.jl:173
 in save_ at /home/yakir/.julia/v0.4/ImageMagick/src/ImageMagick.jl:146
 in save at /home/yakir/.julia/v0.4/ImageMagick/src/ImageMagick.jl:64
 in save at /home/yakir/.julia/v0.4/FileIO/src/loadsave.jl:92
 in save at /home/yakir/.julia/v0.4/FileIO/src/loadsave.jl:51
ERROR: KeyError: RGBA not found
 in setimagecolorspace at /home/yakir/.julia/v0.4/ImageMagick/src/libmagickwand.jl:309
 in constituteimage at /home/yakir/.julia/v0.4/ImageMagick/src/libmagickwand.jl:196
 in image2wand at /home/yakir/.julia/v0.4/ImageMagick/src/ImageMagick.jl:173
 in save_ at /home/yakir/.julia/v0.4/ImageMagick/src/ImageMagick.jl:146
 in save at /home/yakir/.julia/v0.4/ImageMagick/src/ImageMagick.jl:64
 in save at /home/yakir/.julia/v0.4/FileIO/src/loadsave.jl:92
 in save at /home/yakir/.julia/v0.4/FileIO/src/loadsave.jl:51
```

**Comment by SimonDanisch** [comment]
Yeah, there is no RGBA in https://github.com/JuliaIO/ImageMagick.jl/blob/master/src/libmagickwand.jl#L93:
```Julia
const IMColorspace = ["RGB", "Gray", "Transparent", "OHTA", "Lab", "XYZ", "YCbCr", "YCC", "YIQ", "YPbPr", "YUV", "CMYK", "sRGB"]
const IMColordict = Dict([(IMColorspace[i], i) for i = 1:length(IMColorspace)])
```
Inserting it seems to solve this.
@timholy, since this seems to be forgotten, are there also other formats missing?
I'm not really sure what this dict represents ;)

**Comment by timholy** [comment]
Anything related to ImageMagick should now be reported in the new [ImageMagick package](https://github.com/JuliaIO/ImageMagick.jl). Fixed in https://github.com/JuliaIO/ImageMagick.jl/pull/16

**Comment by timholy** [comment]
> I'm not really sure what this dict represents ;)

The "lovely" :wink: ImageMagick [documentation](http://www.imagemagick.org/api/magick-image.php#MagickSetImageColorspace) and [source code docs](http://www.imagemagick.org/api/MagickCore/colorspace_8h.html#a5d516b430fa42c1f83b557f08128f3c2) make it clearer.
