### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by mbauman** [timholy/Images.jl#397]
I made a brief foray into using Images… and one thing I needed was image rotation.  Perhaps I'm missing something, but I couldn't find any existing code for this.  In fact, I'm not quite sure where it should live.  I ended up writing my own simple method that punts to Interpolations… and doesn't even have any dependence on Images.jl at all!  Which makes finding a home for this a little more confusing.  Although, as I write this, I see that you're going to be depending upon Interpolations soon here, which may simplify the choice a bit.

In any case, here's the fly-by code dump.  Feel free to use (MIT license), modify, or discard as you see fit.
```jl
"""
Rotate a matrix. Note that by default, this does not increase the
size of the returned image, so it crops portions that rotate outside the viewport

Optional keyword arguments:
* origin - a tuple of indices (x,y) about which the matrix should rotate
* region - a tuple of UnitRanges to specify the indices of the new image, with respect to the indices of the current one
* fill - the extrapolation fill spec

Note: Unless you compose a rotation as a combination of three
rounded skews, rotations need to be interpolated. So we flip the problem around and
instead rotate the indices into the array, allowing us to punt to Interpolations.
"""
function rotate{T}(im::AbstractMatrix{T}, θ;  # Maybe import Graphics: rotate?
        origin=(size(im, 1)/2+0.5, size(im, 2)/2+0.5),
        region::NTuple{2, UnitRange{Int}}=(1:size(im, 1), 1:size(im, 2)),
        fill=zero(T))
    etp = extrapolate(interpolate(im, BSpline(Linear()), OnGrid()), fill)

    out = similar(im, length(region[1]), length(region[2]))
    x₀, y₀ = origin
    sinθ, cosθ = sin(-θ), cos(-θ) # trickery: angle is negative since we're rotating the indices
    for (ix, x) in enumerate(region[1])
        for (iy, y) in enumerate(region[2])
            # Unwrap the rotation multiplication [cosθ sinθ; -sinθ cosθ]*[x̂, ŷ] to prevent allocating
            x̂, ŷ = x - x₀, y - y₀
            x′ =  cosθ*x̂ + sinθ*ŷ
            y′ = -sinθ*x̂ + cosθ*ŷ
            out[ix,iy] = etp[x′ + x₀, y′ + y₀]
        end
    end
    
    out
end
```

And here's a quick demo of 5, 10 degree rotations at various origins.

![rotation gif](https://cloud.githubusercontent.com/assets/154641/11097651/7f1c9d48-886e-11e5-9546-1ea6d2c8223b.gif)

**Comment by timholy** [comment]
There's an unadvertised `TransformedArrays` capability in `AffineTransforms.jl`. While there is no mention in the README, there are internal docstrings. Try `?transform`.

**Comment by lucasb-eyer** [comment]
Oh wow that's fantastic, I didn't even know about `AffineTransforms.jl` and would never have found it! I think it's worth documenting `TransformedArrays` and advertising that package in `Image.jl`'s readme. (I know, I know, time is limited.)

**Comment by mbauman** [comment]
:+1:.  That's just what I had been looking for, and more general, too.  I should have figured that you had done this already.  :)
