### ISSUE TITLE
Morphology-based Operations

### ISSUE THREAD

**Issue by pratapvardhan** [timholy/Images.jl#402]
I was looking for mathematical morphology support in Images.jl and found base operations (dialtion, erosion, opening, closing).

Before I take a stab at additional morphology functions, wanted to check, if the community is open for these to be added to the library. I've just started using/looking into Images.jl

List of morphological functions:
- [x] [morphgradient](https://en.wikipedia.org/wiki/Morphological_gradient) -  Morphological gradient
- [x] [morphlaplace](http://www.mif.vu.lt/atpazinimas/dip/FIP/fip-Morpholo.html#Heading107) - morphologically-based Laplacian filter
- [x] [tophat](https://en.wikipedia.org/wiki/Top-hat_transform) - Top-hat filtering
- [x] [bothat](https://en.wikipedia.org/wiki/Top-hat_transform) - Bottom-hat filtering

**Comment by timholy** [comment]
Yes, these would be great.

If you're looking at code in Images, you might notice that there's a lot of use of Base.Cartesian. You might still need it for some operations, but I have on my agenda to rewrite a lot of those algorithms using the CartesianIndex iterators in julia 0.4. Now many more arbitrary-dimensional algorithms can be implemented efficiently without resorting to metaprogramming.

That said, if your intention was to implement them just for 2d, that's also fine. My own work usually involves 3d and 4d (space+time) images, but I don't want to make that a barrier for others for whom that might be irrelevant.

**Comment by juliohm** [comment]
I think this issue can be closed.
