### ISSUE TITLE
ImageMagick installation not found

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#410]
I have ImageMagick installed from the repositories of my distribution, it's working fine as I can reproduce their test case:

```bash
convert logo: logo.gif
identify logo.gif
display logo.gif
```

The root directory for ImageMagick here is `/usr/lib/ImageMagick-6.9.2/`, inside of this directory I have two other subdirectories: `config-Q16HDRI` and `modules-Q16HDRI`. There we can find the `*.so` libraries.

When I try to load a JPG image with Images.jl I get the following:

```julia
load("img.jpg")
WARNING: FileIO.NotInstalledError(:ImageMagick,"")
 [inlined code] from bool.jl:16
 in checked_import at /home/julio/.julia/v0.5/FileIO/src/loadsave.jl:12
 in load at /home/julio/.julia/v0.5/FileIO/src/loadsave.jl:76
 in load at /home/julio/.julia/v0.5/FileIO/src/loadsave.jl:42
 in eval at ./boot.jl:264
Library ImageMagick is not installed but can load format: FileIO.File{FileIO.DataFormat{:JPEG}}("img.jpg")
should we install ImageMagick for you? (y/n):
n
INFO: Not installing ImageMagick
```

I tried setting `MAGICK_HOME` to point to `/usr/lib/ImageMagick-6.9.2` and also tried adding this explicitly to `LD_LIBRARY_PATH`, but It didn't work. Is there anything else I can do to debug and solve this issue?

**Comment by timholy** [comment]
You need to say `Pkg.add("ImageMagick")` (or respond "y" to that query). It's not the ImageMagick lib that's missing, it's the julia package. See https://groups.google.com/forum/#!searchin/julia-users/ImageMagick|sort:date/julia-users/SRQrsrq1MB8/d8tUhsJ4AAAJ.

If you have further trouble, please continue at https://github.com/JuliaIO/ImageMagick.jl

**Comment by juliohm** [comment]
Thank you Tim, I missed that info in the `README.md` of `Images.jl`. Maybe we should emphasize that there is a package `ImageMagick.jl` besides the ImageMagick installation itself.

**Comment by timholy** [comment]
It's quite possible that the README is out of date on this topic. Care to prepare a PR with the information in the place it would have helped you?

**Comment by juliohm** [comment]
I appreciate all the amazing Julia packages you are writing, they are really helping me to move with my research. :+1: Thank you.
