### ISSUE TITLE
rgb2gray not defined

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#411]
I can auto-complete the function name with TAB in the interpreter, but it is not defined:

```julia
rgb2gray(img)
ERROR: UndefVarError: rgb2gray not defined
 in eval at ./boot.jl:263
```

I'm using the latest release: Images 0.5.0

**Comment by timholy** [comment]
Good catch, thanks. That function has been deprecated for a long time, so I removed it recently but forgot to remove the export statement.

Fixed in #412.
