### ISSUE TITLE
Images, ImageView.view change the original variable

### ISSUE THREAD

**Issue by missperovaz** [timholy/Images.jl#414]
I'm a newbie in Julia, I really appreciate if you could help me on this. 

I had issues when using piece of code below. Apparently, the original variable (excm) is changed, so when I type ImageView.view(excm) before and after the routine, it is changed, but I'm only manipulating a copy of it (dmode). I have a similar issue when copying properties of one image to another. 

ImageView.view(excm)
dmode = excm;
for i in 2:206
  for j in 2:206
    surr = length(dmode[i-1:i+1,j-1:j+1] .< 0.2)
    if surr > 4 dmode[i,j] = 0 end
  end
end
ImageView.view(excm)

note: once I ran the code ImageView.view(excm) shows me a modified version of excm, even if I'm modifying dmode only. 

thanks a lot,

**Comment by yuyichao** [comment]
Assignment doesn't create a copy. This also has nothing to do with `Images.jl` in particular. Please use the `julia-users` for general questions.

**Comment by timholy** [comment]
@missperovaz, you may be used to Copy-On-Write, in which case this behavior is surprising. But Julia is more like C/C++ in this regard. It's part of what allows julia to be so efficient (for example, the `push!` function simply isn't possible with COW).

**Comment by missperovaz** [comment]
Thanks @timholy and @yuyichao, I have to rescue the C under the rusty dust of my brain. It is now working, and I'm super happy and thankful. thanks a lot
