### ISSUE TITLE
Hausdorff distance

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#420]
Would you be interested in having the Hausdorff distance in `Images.jl`? http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7053955

It is a famous distance used for object-matching. We can apply it to binary images where active pixels are the points in the set.

I also would like to ask you if you know any other distance that can be applied to continuous images? What is the state of the art in computing similarity between images in computer graphics? Any well-known library (C, C++, Fortran, ...) for that?

**Comment by timholy** [comment]
Would be great!

For the purposes of measuring small differences, we have the function/macro combination `@test_approx_eq_sigma_eps`, which tests the mean square difference after blurring by a specified sigma. It's really intended for testing purposes, to ignore small differences in rendering by, e.g., slightly different versions of the Cairo library. Functions like `sad`, `ssd`, and the filtering function allow you to generalize this in small ways. Aside from that, I don't think there's anything.

**Comment by juliohm** [comment]
Thanks Tim, I will work on it when I have time. Busy week here...

**Comment by juliohm** [comment]
Hi Tim, I added the distance, please let me know if there is something that can be made better or more Julian. We also need to define the methods for the image types in Images.jl.

What is the more general binary image type in Images.jl?
