### ISSUE TITLE
Crop Function?

### ISSUE THREAD

**Issue by xanderdunn** [timholy/Images.jl#421]
Is there a function to crop an `Image`?

I'm hoping to be able to truncate a certain number of dimensions off the left, right, top and bottom sides of an `Image`.  

I wouldn't be surprised if there's some simple matrix kung foo lying around that does this trick, but I haven't managed to find it in the documentation.  Thanks!

**Comment by lucasb-eyer** [comment]
Do you mean like so?

```
im = load("img.png")
crop = im[10:end-10,30:end-40]
```

This is no kung foo, it's covered by the [array indexing section of Julia's manual](http://docs.julialang.org/en/latest/manual/arrays/#indexing).

**Comment by xanderdunn** [comment]
It looks like this is indeed what I needed.  I didn't realize basic array operations were valid on `Image`s.  Thanks!

**Comment by timholy** [comment]
See also `getindexim`, `subim`, and `sliceim`.
