### ISSUE TITLE
How do I get 0.5.0

### ISSUE THREAD

**Issue by cormullion** [timholy/Images.jl#426]
For some reason I'm not getting the latest Images.jl (0.5.0) when I update:

                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "?help" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
     _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
    |__/                   |  x86_64-apple-darwin13.4.0

    julia> Pkg.status("Images")
     - Images                        0.4.50

    julia> Pkg.update()
    INFO: Updating METADATA...
    INFO: Computing changes...
    INFO: No packages to install, update or remove

    julia> Pkg.status("Images")
     - Images                        0.4.50

Is it because I'm still on 0.4.2?

**Comment by timholy** [comment]
Not sure, but try `Pkg.free("Images"); Pkg.update()`?

**Comment by cormullion** [comment]
Hi Tim:

    julia> Pkg.free("Images"); Pkg.update()
    INFO: Freeing Images
    INFO: Downgrading Images: v0.5.0 => v0.4.50
    INFO: Building Homebrew
    INFO: Recompiling stale cache file /Users/pete/.julia/lib/v0.4/JSON.ji for module JSON.
    INFO: Recompiling stale cache file /Users/pete/.julia/lib/v0.4/Compat.ji for module Compat.
    INFO: Recompiling stale cache file /Users/pete/.julia/lib/v0.4/BinDeps.ji for module BinDeps.
    INFO: Recompiling stale cache file /Users/pete/.julia/lib/v0.4/URIParser.ji for module URIParser.
    INFO: Recompiling stale cache file /Users/pete/.julia/lib/v0.4/SHA.ji for module SHA.
    remote: Counting objects: 142, done.
    remote: Compressing objects: 100% (82/82), done.
    remote: Total 142 (delta 111), reused 91 (delta 60), pack-reused 0
    Receiving objects: 100% (142/142), 16.53 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (111/111), completed with 18 local objects.
    From https://github.com/Homebrew/homebrew
       791d9d1..ef21486  master     -> origin/master
    HEAD is now at ef21486 plural: tests added
    HEAD is now at 4a13095 Merge pull request #85 from staticfloat/staging
    INFO: Building Images
    INFO: Updating METADATA...
    INFO: Computing changes...
    INFO: No packages to install, update or remove

    julia> Pkg.status("Images")
     - Images                        0.4.50


It didn't seem to make a difference...

**Comment by timholy** [comment]
Not sure, but perhaps you have some other version of a package which requires an earlier version of Images? If you're on Unix,
```sh
fls=$(find . -name "REQUIR*")
grep Images $fls
```
will work.

**Comment by lucasb-eyer** [comment]
I may be way off, but I noticed `v0.4.50` is the last version to contain `julia 0.3` in its `requires` file in `METADATA.jl`, whereas `v0.5.0` has the line `julia 0.4`.

**Comment by cormullion** [comment]
@timholy Ah, I didn't know that. Makes sense. I'll have a clear out.

You mean things like https://github.com/timholy/ImageView.jl/blob/master/REQUIRE:

    Images 0.4

**Comment by timholy** [comment]
No, that's a minimum version, not a maximum version. See the documentation on the Package manager.

**Comment by cormullion** [comment]
@timholy Problem solved (eventually)! I found that Colors.jl had been marked as "dirty" for some reason and was stuck at 0.5.4, so Images 0.5.0 didn't want to upgrade itself. Thanks for the hints!
