### ISSUE TITLE
save() in 0.5 doesn't work

### ISSUE THREAD

**Issue by cormullion** [timholy/Images.jl#428]
I installed Images.jl version 0.5.0, which has switched to `load()` and `save()`. `load()` works but `save()` doesn't. I'm on OS X, julia 0.4.2.

    julia> using Images

    julia> img = load("/tmp/1.jpg")
    RGB4 Images.Image with:
      data: 1916x800 Array{ColorTypes.RGB4{FixedPointNumbers.UFixed{UInt8,8}},2}
      properties:
        imagedescription: <suppressed>
        spatialorder:  x y
        pixelspacing:  1 1

    julia> save("/tmp/test.jpg", img)
    WARNING: ErrorException("no encode delegate for this image format `MIFF' @ error/constitute.c/WriteImage/1167")
     in error at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in error at /Users/me/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
     in writeimage at /Users/me/.julia/v0.4/ImageMagick/src/libmagickwand.jl:246
     in save_ at /Users/me/.julia/v0.4/ImageMagick/src/ImageMagick.jl:146
     in save at /Users/me/.julia/v0.4/ImageMagick/src/ImageMagick.jl:64
     in save at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:92
     in save at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:51
    ERROR: no encode delegate for this image format `MIFF' @ error/constitute.c/WriteImage/1167
     in error at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in error at /Users/me/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
     in writeimage at /Users/me/.julia/v0.4/ImageMagick/src/libmagickwand.jl:246
     in save_ at /Users/me/.julia/v0.4/ImageMagick/src/ImageMagick.jl:146
     in save at /Users/me/.julia/v0.4/ImageMagick/src/ImageMagick.jl:64
     in save at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:92
     in save at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:51
     
I'm sure I saw this error last year... But it looks like ImageMagick is installed in the right place (although perhaps it wouldn't be needed if Images.jl made OS X make image files?).

`imwrite()` doesn't work either:

    julia> imwrite("/tmp/test.jpg", img)
    WARNING: imwrite(img,filename; kwargs...) is deprecated, use save(filename,img; kwargs...)      instead.
     in depwarn at deprecated.jl:73
     in imwrite at deprecated.jl:50
    
Perhaps I'm missing a kwarg or something?

**Comment by timholy** [comment]
No, you have a borked ImageMagick installation. Images is now independent of ImageMagick, so please open an issue at [ImageMagick.jl](https://github.com/JuliaIO/ImageMagick.jl).

Since you're on OSX, you can also try deleting ImageMagick and installing QuartzImageIO.

**Comment by cormullion** [comment]
@timholy Thanks. Well I got rid of ImageMagick and installed QuartzImageIO, but I suppose I have to do something else, because:

     julia> save("/tmp/test.jpg", img)
    WARNING: FileIO.NotInstalledError(:ImageMagick,"")
     in checked_import at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:12
     in save at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:91
     in save at /Users/me/.julia/v0.4/FileIO/src/loadsave.jl:51
    Library ImageMagick is not installed but can load format: FileIO.File{FileIO.DataFormat{:JPEG}}("/tmp/test.jpg")
    should we install ImageMagick for you? (y/n):

I have added QuartzImageIO and done:

    using Images, QuartzImageIO, FileIO

with apparently no problems reported.

Since Images.jl is no longer doing input and output, should I report this at FileIO or QuartzImageIO instead?  Presumably it's not me that's supposed to register PNG and JPG formats? Documentation is very sketchy now.
