### ISSUE TITLE
Median filter

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#434]
It would be great to have this filter in the package. Do you suggest a reference book or paper describing good algorithms?

**Comment by timholy** [comment]
I suspect the extrema filter contributed in #413 could be modified to achieve this goal, but I haven't played with it myself.

**Comment by juliohm** [comment]
Thank you Tim, I will take a look at it when I find time.

**Comment by juliohm** [comment]
Fixed by https://github.com/JuliaImages/ImageFiltering.jl/pull/14
