### ISSUE TITLE
Load function 

### ISSUE THREAD

**Issue by alexmulo** [timholy/Images.jl#440]
I'am trying to load an image in Julia using the package Images and the function load.

```
julia> load("/train/1.bpm")
ERROR: FileIO.File{FileIO.DataFormat{:UNKNOWN}}("/train/1.bpm") couldn't be recognized by FileIO.
```
I am using Julia 0.4.2.

How can I solve the problem?

Thanks a lot

**Comment by timholy** [comment]
Looks like BPM needs to be added to the registry in [FileIO](https://github.com/JuliaIO/FileIO.jl). Care to give it a shot?

**Comment by timholy** [comment]
Out of curiosity, did you mean "bmp"? If so, one curiosity is why it wouldn't have recognized the [magic bytes](https://github.com/JuliaIO/FileIO.jl/blob/8e6b433fee867915119c0053a50ac4c63196bf1e/src/registry.jl#L71-L77); is it possible your file is corrupted?

**Comment by alexmulo** [comment]
Sorry but yesterday I was too tired to realize that the mistake is "bpm". I am using bmp files. I am sorry.
Thanks for the advice.

**Comment by timholy** [comment]
Looks like the error message is confusing, though; it should first check for the existence of the file, and then worry about the format. I'll try to fix that in FileIO.

**Comment by timholy** [comment]
See https://github.com/JuliaIO/FileIO.jl/pull/54.
