### ISSUE TITLE
restrict automatically add property `pixelspacing:  2.0 2.0` to the image which causes an ImageView error

### ISSUE THREAD

**Issue by Gnimuc** [timholy/Images.jl#442]
for example, let's create a random gray image:
```julia
julia> testImg = Image(rand(128,128), Dict("colorspace"=>"Gray", "spatialorder"=>"y x"))
Gray Images.Image with:
  data: 128x128 Array{Float64,2}
  properties:
    colorspace: Gray
    spatialorder: y x
```
then, resize it to be a smaller one
```julia
julia> bugImg = Images.restrict(testImg)
Gray Images.Image with:
  data: 65x65 Array{Float64,2}
  properties:
    colorspace: Gray
    spatialorder: y x
    pixelspacing:  2.0 2.0
```
note that, the `pixelspacing:  2.0 2.0` was added but the original image do not have this property.
```julia
julia> view(bugImg)
ERROR: BoundsError: attempt to access 2-element Array{Float64,1}:
 2.0
 2.0
  at index [1,2,3]
 in throw_boundserror at abstractarray.jl:156
 in getindex at abstractarray.jl:488
 in call at /Users/gnimuc/.julia/v0.4/ImageView/src/display.jl:159
 in view at /Users/gnimuc/.julia/v0.4/ImageView/src/display.jl:239
```
and ImageView will complain this unless i manually make it a 3-element vector: 
```
`bugImg["pixelspacing"] = [2,2,2]
```
i'm wondering what happened under the hood, this behavior looks wired.

**Comment by timholy** [comment]
Your `spatialorder` should be `["y", "x"]`, not `"y x"`. I guess the Image constructor should check for that.

**Comment by Gnimuc** [comment]
Oops! what a stupid mistake :dizzy_face: sorry for disturbing

**Comment by timholy** [comment]
It shouldn't be quite so easy to make such mistakes, and in this case the way properties are printed adds to the potential for confusion.
