### ISSUE TITLE
 using Images INFO: Precompiling module Images... ERROR: LoadError: LoadError: Images not properly installed. Please run Pkg.build("Images") then restart Julia.

### ISSUE THREAD

**Issue by wwang2** [timholy/Images.jl#444]
It is really strange. The Image package was fine about two weeks ago, when I typed `using Images`, it gives some compilation error I did not have before. It exists even after I re-install Julia.

`INFO: Precompiling module Images...
ERROR: LoadError: LoadError: Images not properly installed. Please run Pkg.build("Images") then restart Julia.`

I have no clue how to resolve this..

**Comment by lucasb-eyer** [comment]
Did you try what it asks you: run `Pkg.build("Images")`? If so, what's the output of that?

**Comment by wwang2** [comment]
Yes. I have something like this...

`INFO: Building Homebrew
HEAD is now at 31a0c7a opus: audit fixes
HEAD is now at 4a13095 Merge pull request #85 from staticfloat/staging
INFO: Building Images
==> Installing imagemagick from staticfloat/juliadeps
Error: undefined method `<' for nil:NilClass`

**Comment by timholy** [comment]
Images doesn't depend on ImageMagick anymore; in fact, Images doesn't even have a build script anymore. `Pkg.status()` will probably tell you that something is dirty or that you're following a branch, or perhaps it's just that you haven't updated in a long time.
