### ISSUE TITLE
imfilter_gaussian! unexpectedly mutates the validpixels matrix

### ISSUE THREAD

**Issue by tom--lee** [timholy/Images.jl#452]
I found it surprising when I tried to use the same `validpixels` mask multiple times and got strange result. Not sure if its easy to fix this without copying the `validpixels` matrix.

**Comment by timholy** [comment]
That's unavoidable. It basically works like `nanmean`, `sum(a[valid])/sum(valid)`. But with filtering, it has to filter the valid-pixel mask so that it spreads in the same way real pixels do.

You could filter just the numerator (`data`) and divide by the denominator yourself.
