### ISSUE TITLE
GSoC Proposal

### ISSUE THREAD

**Issue by mronian** [timholy/Images.jl#453]
I am interested in applying to Julia with a proposal for Images.jl

The ideas page on julialang.org has a [project proposal](http://julialang.org/soc/ideas-page.html#writing-high-performance-multithreaded-kernels-for-image-processing) for writing high performance multithreaded kernels for image processing, more specifically multithreaded versions of `imfilter` and `imfilter_gaussian`. 

I am also interested in adding functionality to Images.jl like Image Stitching, Face Detection, Object Tracking, Feature Descriptors or Drawing Functions. 

Which project would be higher in the priority list?

**Comment by timholy** [comment]
Thanks for your interest @mronian. You raise some good questions. Overall I tend to think that some features, like face detection, are sufficiently specialized that they would like best be in a separate repository. https://github.com/JuliaImages is not yet populated, but perhaps that should change.

**Comment by mronian** [comment]
Is https://github.com/JuliaImages planned to be a umbrella organisation for all image processing repositories?

Am I correct in interpreting JuliaImages as equivalent to OpenCV while Images.jl is equivalent to the imgproc component of OpenCV?

Maybe I could work on populating JuliaImages with the various functions taking a cue from other popular image processing libraries.

**Comment by lucasb-eyer** [comment]
Thanks @timholy for this policy, I fully agree. I've used OpenCV a lot and I don't think it's an example to follow here.

**Comment by mronian** [comment]
I would like to work on 2D Feature extraction for Images.jl, more specifically the following algorithms : 

- Canny
- Corner Harris
- Shi-Tomasi Corner Detector
- SIFT Descriptor
- SURF Descriptor
- ORB Descriptor
- GLCM Matrix
- Descriptor Matching Function

@timholy Does this seem like a good project to work on?

**Comment by timholy** [comment]
Yes, absolutely! But some of this may already be available. See `src/corner.jl`, for example. Also see #441.

**Comment by bjarthur** [comment]
@mronian  you should coordinate with [ImageRegistration.jl](https://github.com/seung-lab/ImageRegistration.jl).  they specifically mention SURF/SIFT.

**Comment by mronian** [comment]
@bjarthur ImageRegistration.jl seems to be a library for calculating projective transformation of one image to another. Adding SIFT/SURF to Images.jl will be better as otherwise a person will need to add the ImageRegistration package just for feature extraction even though he may have no intention of doing projective transformations. This will make it usable for general purposes as a person will have Images.jl installed anyway if he is planning to do image processing. Does this seem alright? I have opened an [issue \#2](https://github.com/seung-lab/ImageRegistration.jl/issues/2) on the ImageRegistration repo to get their opinion on this. 

@timholy As Corner Harris and Shi-Tomasi are already implemented, I am adding the functions for calculating the texture properties of GLCM, local binary patterns, BRIEF descriptor and CENSURE keypoint detector to my proposal. Instead I could also work on adding drawing functions alongwith the original 2D features I mentioned above to Images.jl which will add line, ellipse, polygon drawing functions (I don't know if these would be suitable in Image.jl itself or a separate repo for drawing functions). I also didn't find exposure correcting functions like histogram equalisation/matching, gamma correction or the CLAHE algorithm.

**Comment by timholy** [comment]
I kind of like the idea of an ImageFeatures.jl package that focuses on these kinds of descriptors. I think it's different enough from ImageRegistration.jl that it would be better to separate out.

Image drawing would also be fine, but I suspect the computer vision tools would have substantially greater impact. (There's a little bit of annotation added in ImageView.jl, which is long overdue for a rewrite.) In the end, you should propose what you think best fits your interests and expertise.

Naturally, I'm happy to mentor work on image processing even if it isn't part of Images.jl itself. I think package organization should be driven by the criterion of what makes most sense. My personal experience is that focused packages often seem to work better than monolithic ones.

**Comment by mronian** [comment]
I was going through some discussions on implementation of SIFT/SURF in other packages and I came to know that they are patented and cannot be used without the author's permission. Though OpenCV has the functions, they state that to use them you need to obtain permission. I found a [discussion on their usergroup](http://opencv-users.1802565.n2.nabble.com/SURF-protected-by-patent-td3458734.html) on this issue. Scikit-Image does not include SIFT or SURF for the same reason. I also came across other algorithms which are not only free to use but also said to be better for feature description like BRISK and FREAK. I would like to work on them instead of SIFT or SURF so that the code is open source in the true sense and there are no patent issues. What do you think?

I have made a draft of my proposal which can be found here : [GSoC Proposal](https://docs.google.com/document/d/1XD_fpT6YpyK6Iv2Rues2RlU-15l4aBbUZTSz1V216pw/edit?usp=sharing). I am still filling out some of the parts.

@timholy , @bjarthur I would be grateful if you could provide your valuable inputs on my proposal before I submit it. The deadline is 25th March and I'd like to make the best use of the next few days to work on my proposal. Inline commenting is enabled in the Google Doc. I look forward to you comments :)

**Comment by mronian** [comment]
I'd like to add that many of the algorithms are feature descriptor only, they don't talk about feature detection. Maybe I could replace some with feature detection algorithms like FAST or AGAST to ensure we have a good mix of both.

**Comment by timholy** [comment]
Wow. Absolutely, let's not devote any effort to encumbered algorithms. What an insanse practice.

**Comment by SimonDanisch** [comment]
Hey I created a package really quickly, to demonstrate that we could just use OpenCL kernels from:
[gegl](https://github.com/OpenCL/GEGL-OpenCL/tree/master/opencl) and [OpenCV](https://github.com/Itseez/opencv/tree/ddf82d0b154873510802ef75c53e628cd7b2cb13/modules/features2d/src/opencl).
It's really quick and dirty, the name is for debate, but maybe we could polish this up over the course of GSoC.

https://github.com/JuliaImages/ImageCL.jl

**Comment by mronian** [comment]
@SimonDanisch , @timholy : Is this a better way to execute my proposal than writing them from scratch? Should I add this to the implementation part of my proposal? I have around 1.5 days to go before the deadline. 

Thanks @SimonDanisch for creating the package, it helped me understand how this would work somewhat :)

**Comment by SimonDanisch** [comment]
up to you and @timholy! I'm not sure what the most important item on the `Images` roadmap is!
I guess I'll slowly populate this Package for my Vulkan work anyways (You should be able to also launch OpenCL kernels with [Vulkan](http://randomfantasies.com/2016/02/why-im-betting-on-vulkan-and-julia/)). 
I think you should at least try to use it as a baseline when benchmarking your algorithms! What would be nice to find out is, how the speed differences are on a low end GPU like an intel onboard and when using a CPU OpenCL backend compared to the Julia CPU version.
Another thing to look out for is the licensing. I'm not entirely sure if copying the kernel and leaving the copyright note in the file suffices!

**Comment by timholy** [comment]
I like the idea of leveraging the GPU, but I think we have to support operations on the CPU too. In other words, maybe an ideal to strive for is a (reasonably) common API between CPU and GPU for these computations.

Nice proposal, @mronian.

**Comment by mronian** [comment]
Thanks @timholy :)

Would it be alright if I put your name as a mentor for my proposal as given in the GSoC guidelines on the Julia website?

**Comment by timholy** [comment]
Sure. If you end up doing a lot of GPU stuff, @SimonDanisch would be awesome to have on board. Fortunately, the julia community has a lot of expertise and hopefully many can chime in.

**Comment by SimonDanisch** [comment]
I wouldn't mind helping out a bit ;) By the way, OpenCL runs also on the CPU :P But obviously, not everyone has the driver installed.

**Comment by mronian** [comment]
Thanks a lot :)

**Comment by mronian** [comment]
It feels great to be selected. Thanks a lot @timholy and @SimonDanisch  for guiding me through everything. I am really lucky to get mentors like you. Looking forward to a great summer :)

**Comment by timholy** [comment]
Congrats! Excited to have you aboard.

**Comment by mronian** [comment]
@timholy My exams got over today and I'd like to start with planning the details of ImageFeatures.jl. What would be a good place to have the discussions? Would you be available on the Slack Group where the Julia GSocers and mentors are added? I could not find you there. We could also use Gitter since it directly connects to Github.

**Comment by mronian** [comment]
@timholy Should I make a standalone ImageFeatures.jl repository? I was thinking it would be better if we could add it to the JuliaImages organisation on Github as part of the larger plan of having all image processing related libraries under that. Also this way the documentation can have a common theme for all libraries so anyone who wants to know about image processing with julia can go to a single website.

**Comment by timholy** [comment]
I made one this morning. You should have a pending invitation to join JuliaImages (sent some time ago by SimonDanisch, I suspect). If you accept that you should have direct push access.

In case it helps: once you locally do a `Pkg.generate("ImageFeatures", "MIT")`, then push it like this:
```jl
git remote add origin https://github.com/JuliaImages/ImageFeatures.jl.git
git push -u origin master
```

**Comment by mronian** [comment]
Thanks for making the ImageFeatures.jl repository! 

I haven't received the invitation to join JuliaImages yet. I tried making an initial commit to ImageFeatures but I am getting a permission denied error. @SimonDanisch it would be great if you could please check if I was added and resend the invite. Thanks :)

**Comment by SimonDanisch** [comment]
@mronian, I updated the invitation... Not sure what Github means by that, though ;)

**Comment by mronian** [comment]
Thanks @SimonDanisch :) but it doesn't seem to have gone through. There is no notification even in the Github notifications manager. Since there is no code in the repository, I can neither fork it nor submit a PR. Could you add some dummy file to the repo so that I can see if it allows me to merge a simple PR on Github itself by editing that file?

**Comment by SimonDanisch** [comment]
This should go to the email address that you have registered with github...

**Comment by mronian** [comment]
Yes. I checked the junk folder too but could not find an invite. I know the same email address has worked in the past since Tim had given me push access to TestImages.jl and I had obtained the permissions.

**Comment by mronian** [comment]
I found the invite after following this -> https://github.com/blog/1868-inviting-people-to-your-organization

Turns out the invite appears on the organisation github page :) Thanks a lot!

**Comment by mronian** [comment]
Though tutorials was one of the stretch goals in the proposal, I'll try adding small ones as I code. I am putting them [here](https://drive.google.com/folderview?id=0B0RbpETLIN25Z2oyZW1Ma1kwVFU&usp=sharing) till a suitable place is found.
