### ISSUE TITLE
Error during compilation after modifying algorithms.jl

### ISSUE THREAD

**Issue by mronian** [timholy/Images.jl#457]
I am working on adding a histogram equalisation function to help me get started with my GSoC Proposal. I made the changes in src/algorithms.jl and added some tests in test/algorithms.jl. I made changes to the docs in docs/src/function_reference.md. 

Now when I do ```using Images```, the compilation fails. What am I doing wrong?

This is the error :

```
ERROR: LoadError: LoadError: UndefVarError: T not defined
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in eval(::Module, ::Any) at ./boot.jl:267
 [inlined code] from ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jarvis/.julia/v0.5/Images/src/algorithms.jl, in expression starting on line 458
while loading /home/jarvis/.julia/v0.5/Images/src/Images.jl, in expression starting on line 39
ERROR: Failed to precompile Images to /home/jarvis/.julia/lib/v0.5/Images.ji
 in error(::ASCIIString) at ./error.jl:21
 in compilecache(::ASCIIString) at ./loading.jl:496
 in compilecache(::Symbol) at ./loading.jl:485
 in require(::Symbol) at ./loading.jl:355
 in eval(::Module, ::Any) at ./boot.jl:267
```

**Comment by bjarthur** [comment]
the error occurs on line 458 of algorithms.jl.  is that where you made changes?  show us if so by making a gist.

**Comment by mronian** [comment]
I got the error. My knowledge on julia abstract datatypes was not clear. Thanks!

**Comment by mronian** [comment]
@bjarthur Once I've added the function, how do I call it directly without using ```Images.function_name``` everytime ?
