### ISSUE TITLE
GSoC Proposal (2)

### ISSUE THREAD

**Issue by raphapr** [timholy/Images.jl#459]
Hi, I was very interested in working on the project proposal that I found on julia page: [Writing high-performance, multithreaded kernels for image processing](http://julialang.org/soc/ideas-page.html#writing-high-performance-multithreaded-kernels-for-image-processing).

I am comfortable with the julia language and have a little experience for the same, I also have done some research projects where I was engaged in processing huge images (Polarimetric SAR Data).

I am writing this proposal under tight deadline and would know if someone could guide me regarding this project, what all things should start studying, in a technical way?

Anyway, my proposal can be found here: [GSoC proposal project](https://docs.google.com/document/d/1K8ZbHE6Zo0UdfDxj3W65SVgCg7aKgiJcUCyHAiduFEA/edit?usp=sharing) (not completed yet), and I would really appreciate any feedback you guys can give me (:

(I don't know if this is the right place for this but I was encouraged after reading https://github.com/timholy/Images.jl/issues/453)

**Comment by timholy** [comment]
Sorry I didn't get to this more quickly; yesterday was very busy and I just couldn't keep track of all the emails.

**Comment by raphapr** [comment]
That's ok! I had closed the issue because already submitted the proposal.

**Comment by timholy** [comment]
Oh, great! Good luck!
