### ISSUE TITLE
imcomplement causes a MethodError

### ISSUE THREAD

**Issue by ararslan** [timholy/Images.jl#461]
If I load some PNG file and try to invert it using `imcomplement`, I get a `MethodError`. It looks like `imcomplement` is just doing `1 - element` for each element in the input array, but there's no subtraction method defined for the element type of the array with an integer.

```julia
julia> using FileIO

julia> using Images

julia> a = load("a.png")
RGBA Images.Image with:
  data: 1400x699 Array{ColorTypes.RGBA{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> imcomplement(a.data)
ERROR: MethodError: `.-` has no method matching .-(::Int64, ::ColorTypes.RGBA{FixedPointNumbers.UFixed{UInt8,8}})
Closest candidates are:
  .-(::Real, ::FloatRange{T<:AbstractFloat})
  .-(::Real, ::LinSpace{T<:AbstractFloat})
  .-(::Real, ::Range{T})
  ...
 in .- at arraymath.jl:120
 in imcomplement at /Users/ararslan/.julia/Images/src/algorithms.jl:1334
```

I don't know whether that's something that should have been defined in `ColorTypes` or handled in `Images` but I figured I'd bring it up here.

Images 0.5.3, Julia 0.4.5, OS X 10.10

**Comment by ararslan** [comment]
Replacing 1 with `one(eltype(img))` in `imcomplement` gets part of the way there. The challenge then is that the alpha gets messed up. For example, if `img` has all `ColorTypes.RGBA{FixedPointNumbers.UFixed{UInt8,8}}`, calling `one` for this type sets the alpha to 1, so subtracting other RGBA values with an alpha of 1 is no bueno.

**Comment by timholy** [comment]
You tried the right fix.

But maybe backing up is the first step: what do you think this function should do with an `RGBA`? In particular, how should the alpha channel be handled?

**Comment by ararslan** [comment]
When I think of an image's complement I think of color inversion, not alpha inversion. So in that regard I would think that the alpha would be left untouched. (Which then becomes more complicated in terms of constructing an inverse since it's not just `one` for that type.) I'm certainly not an expert though. :wink:
