### ISSUE TITLE
Error while reading image 

### ISSUE THREAD

**Issue by MaluPunnackal** [timholy/Images.jl#464]
Hi Friends,

I am trying to test the implementation of character recognition using Julia in my Windows 10 machine using the tutorial from https://www.kaggle.com/c/street-view-getting-started-with-julia/data

Below is the code which I am using to implement it. 

Pkg.add("Images")
Pkg.add("DataFrames")

using Images
using DataFrames
using Images.ColorTypes
using FixedPointNumbers
using Iterators

function read_data(typeData, labelsInfo, imageSize, path)
	x = zeros(size(labelsInfo, 1), imageSize)                   

	for (index, idImage) in enumerate(labelsInfo[:ID]) 
	nameFile = "$(path)\\$(typeData)Resized\\$(typeData)Resized\\$(idImage).bmp"
	img = load(nameFile)                                                            
	temp = convert(Image{Gray}, img)                                                
    x[index, :] = reshape(temp, 1, imageSize)                                       
	end                                                                               
  return x
end

imageSize = 400                                                                     

path = "...."                                                 
println(path)
labelsInfoTrain = readtable("$(path)\\trainLabels.csv")                              
xTrain = read_data("train", labelsInfoTrain, imageSize, path)                       

yTrain = map(x -> x[1], labelsInfoTrain[:Class])                                     
yTrain = int(yTrain)                                                                 

labelsInfoTest = readtable("$(path)\\sampleSubmission.csv")                          
xTest = read_data("test", labelsInfoTest, imageSize, path)                          

Pkg.add("DecisionTree")
using DecisionTree

model = build_forest(yTrain, xTrain, 20, 50, 1.0)

predTest = apply_forest(model, xTest)

labelsInfoTest[:Class] = char(predTest)
writetable("$(path)\\juliaSubmission.csv", labelsInfoTest, header=true, separator=',')

Below is the error I am getting while implementing the code 

WARNING: ErrorException("unable to open image `C:\\Users\\user\\Desktop\\SPL-TermProject-master\\OCR_test\\testResized\\testResized\\10000.bmp': No such file or directory @ error/blob.c/OpenBlob/2702")
 in error at error.jl:21
ERROR: LoadError: unable to open image `C:\Users\user\Desktop\SPL-TermProject-master\OCR_test\testResized\testResized\10000.bmp': No such file or directory @ error/blob.c/OpenBlob/2702
 in error at error.jl:21
while loading C:\Users\user\Desktop\SPL-TermProject-master\OCR_test\Forest.jl, in expression starting on line 34

I am new to Julia and I really appreciate any help you could provide on this

Thanks & Regards,

Malu

**Comment by SimonDanisch** [comment]
I admit that the error messages are not very beautiful, but the most important bit is there:

```Julia
C:\\Users\\user\\Desktop\\SPL-TermProject-master\\OCR_test\\testResized\\testResized\\10000.bmp': No such file or directory @ error/blob.c/OpenBlob/2702") in error at error.jl:21 ERROR: LoadError: unable to open image
C:\Users\user\Desktop\SPL-TermProject-master\OCR_test\testResized\testResized\10000.bmp': No such file or directory 
```

**Comment by MaluPunnackal** [comment]
Yes there is no such file as 10000.bmp. I am trying to train my system with sample images but I am not sure from where it is getting this data

**Comment by vchuravy** [comment]
Kaggle has bunch of zips that probably contain the training and test images. You will have to unpack them.

**Comment by MaluPunnackal** [comment]
I have unzipped all those images and have kept it in correct location and the code which I am trying is getting implemented in MAC by I am facing issue only in Windows machine

**Comment by vchuravy** [comment]
The issues of a package are the wrong place to discuss this kind of problem (see one of the user mailing list next time :) )

But the error arises in the following function:
```julia
function read_data(typeData, labelsInfo, imageSize, path)
  x = zeros(size(labelsInfo, 1), imageSize)

  for (index, idImage) in enumerate(labelsInfo[:ID]) 
    nameFile = "$(path)\\$(typeData)Resized\\$(typeData)Resized\\$(idImage).bmp"
    img = load(nameFile)                                                            
    temp = convert(Image{Gray}, img)                                                
    x[index, :] = reshape(temp, 1, imageSize)                                       
  end
end
```

If you replace this with this
```julia
function read_data(typeData, labelsInfo, imageSize, path)
  x = zeros(size(labelsInfo, 1), imageSize)

  if !ispath(path)
     error("$path is not valid.")
  end

  for (index, idImage) in enumerate(labelsInfo[:ID]) 
    nameFile = "$(path)\\$(typeData)Resized\\$(typeData)Resized\\$(idImage).bmp"
    if isfile(nameFile)
      img = load(nameFile)                                                            
      temp = convert(Image{Gray}, img)                                                
      x[index, :] = reshape(temp, 1, imageSize)
    else
      warn("$file does not exist")
    end                                      
  end
end
```

you get a better understanding where the error is coming from. 

Instead of 
```julia
nameFile = "$(path)\\$(typeData)Resized\\$(typeData)Resized\\$(idImage).bmp"
```

use:
```
namefile = joinpath(path, "$(typeData)Resized",  "$(typeData)Resized", "$(idImage).bmp")
```
this will work across systems.

The problem right now doesn't seem to be with your julia code, but rather that your filesystem layout doesn't fit with what the program expects.

**Comment by SimonDanisch** [comment]
I'm closing this, since this isn't an issue with Images.jl.
If you still have problems, please use [julia-users](https://groups.google.com/forum/#!forum/julia-users) or even better the kaggle forum!
