### ISSUE TITLE
imadustintensity() underflow error

### ISSUE THREAD

**Issue by bjarthur** [timholy/Images.jl#470]
note the lower left value in this 2x2 matrix example.  when adjusted it should be 0 because it is less than the range:

```
julia> img
2x2 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},2}:
 Gray{UFixed16}(0.01164)  Gray{UFixed16}(0.01118)
 Gray{UFixed16}(0.01036)  Gray{UFixed16}(0.01187)

julia> imadjustintensity(img, [Gray{Float64}(0.0103761), Gray{Float64}(0.0252166)])
2x2 Array{Float64,2}:
 0.0853407  0.0544947
 1.0        0.100764 
```

it comes out 1 because the type of the range is converted to match the image, and the subsequent fixedpoint subtraction underflows:

```
julia> convert(Gray{UFixed16}, Gray{Float64}(0.0103761))
Gray{UFixed16}(0.01038)

julia> img[2,1] - ans
Gray{UFixed16}(1.0)
```

the alternate way to adjust intensity doesn't have this problem:

```
julia> map(ScaleMinMax(Gray{UFixed16}, Gray{Float64}(0.0103761), Gray{Float64}(0.0252166)), img)
2x2 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},2}:
 Gray{UFixed16}(0.08534)  Gray{UFixed16}(0.05449)
 Gray{UFixed16}(0.0)      Gray{UFixed16}(0.10077)
```

given "This [i.e. imadjustintensity] is equivalent to `map(ScaleMinMax(T, minval, maxval), img)`" according to the docstring, why not just define:

```
imadjustintensity{T}(img::AbstractArray{T}, range) = map(ScaleMinMax(T, range...), img)
```

historical artifact?

**Comment by timholy** [comment]
Yes, historical artifact.

**Comment by timholy** [comment]
(`imadjustintensity` predates my involvement with Images.)

**Comment by bjarthur** [comment]
i'm inclined to redefine `imadjustintensity` as i suggested unless the original author steps up to defend it.  it's nice to have the shorthand convenience function, but there's no sense in duplicating code, particularly when it's buggy.

i also meant to mention that the `map(ScaleMinMax...` alternative is nicer too in that it preserves the `eltype`.

**Comment by timholy** [comment]
Yeah, I think you can just go ahead and do that.

**Comment by bjarthur** [comment]
fixed with https://github.com/timholy/Images.jl/pull/472
