### ISSUE TITLE
Is there any way to get a 2D 0-255 array from images?

### ISSUE THREAD

**Issue by raphsoft** [timholy/Images.jl#479]
I've tried so many ways without luck. So my question is just simple: Is there any way to get a 2D 0-255 array from images? Even if I try the following:

```
grayImage=convert(Array{Gray},initiaImage)
array1 = grayImage[:,:]*255
```

I do get this message:
```
WARNING: Mapping to the storage type failed; perhaps your data had out-of-range values?
Try `map(Images.Clamp01NaN(img), img)` to clamp values to a valid range.
InexactError()
WARNING: InexactError()
```

A simple function in matlab for the same task will be:
```
function out = rgb2gray(in)
in = double(in);
out = 0.2989 * in(:,:,1) + 0.5870 * in(:,:,2) + 0.1140 * in(:,:,3);

```

**Comment by timholy** [comment]
Can you provide a standalone script (something that I can run myself) that triggers these errors? They all depend on how `initialImage` and `grayImage` are defined.

In exchange, here's an example that works:
```jl
julia> using TestImages

julia> imgrgb = testimage("mandrill")
RGB Images.Image with:
  data: 512x512 Array{ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: sRGB
    spatialorder:  x y

julia> imgg = convert(Image{Gray}, imgrgb)
Gray Images.Image with:
  data: 512x512 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: sRGB
    spatialorder:  x y
```

Specifically regarding your "255" request: one of the things I find really annoying about matlab's image-handling is that for an image constructed with `uint8`, 0=black and 255=white. Convert it to a `double`, and now 0=black and 1=white. If you're writing code that takes a `threshold` argument, you have to know to supply different thresholds for different representations of what's actually just the same data. Very annoying.

In contrast, Images.jl (via ColorTypes.jl) always uses 1=white, even when only one byte/pixel is being used. The trick is the use of a special number type, `UFixed8`, which is a [fixed-point](https://en.wikipedia.org/wiki/Fixed-point_arithmetic) real number (fixed-point is like floating-point, except, well, fixed).

You can always use `raw` to convert back to types that may be more familiar to you. But I find that once you get used to it this new way is much nicer.

**Comment by raphsoft** [comment]
Convert works well, I can get the gray image but my issue is that it should be very easy to get image's histogram from a 0-255 int array by doing something like this 
```
my_histrogram = zeros(255)

for i=1:255
   for j=1:255
      my_histrogram[gray255_img[i,j]] = my_histrogram[gray255_img[i,j]] + 1
   end
end
```

Then I will be able to equalize my image's histogram and get a better image (given that my input image is a overexposed one)

**Comment by timholy** [comment]
Ah, you're just looking for #458. Yes, we should finish that off and merge it.

**Comment by raphsoft** [comment]
Well, if you plan to have a built-in function for histogram equalization that's fine but it will still be a little hard do to some other basic computation on images. I could convert the UFixed8 to Int32 but when doing so, it takes a lot of time compared to (sorry for this) matlab. Or... maybe I just need more practice.

I've seen I need to call a function to apply filters on images. I guess I'll have the same problem if I just want to go myself and perform matrix operations.

Anyway, thanks for taking the time for replying my question.

**Comment by raphsoft** [comment]
I realized that the conversion to Gray is very helpful, I finally did something like:

```
grayImage = convert(Image{Gray},rgbImage)
imgMatrix = convert(Array{Int32},raw(grayImage))
``` 

Thank you!

**Comment by timholy** [comment]
Or try `raw`.

But I still don't understand the problems you're having. For example:
```jl
julia> img = grayim(rand(UInt8,4,7))
Gray Images.Image with:
  data: 4x7 Array{FixedPointNumbers.UFixed{UInt8,8},2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> 20*img
Gray Images.Image with:
  data: 4x7 Array{Float64,2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> img*20
Gray Images.Image with:
  data: 4x7 Array{Float64,2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> img[:,:]*20
4x7 Array{Float64,2}:
 19.6863   9.2549    14.9804    16.4706     1.72549  13.8824   5.17647
 10.5882   0.705882   5.41176   10.2745     6.90196  18.902   18.5882 
 15.6078  13.5686     0.705882   0.470588  16.7843   14.0392  16.8627 
 11.3725   4.07843    9.17647    6.35294   18.0392   11.1373  13.4118 
```
That's why it would be really helpful if you specified in full detail where your image is coming from, or posted it somewhere for me to download. Try as I might, I simply cannot replicate the problems you're having.

**Comment by timholy** [comment]
Are you using IJulia??

**Comment by timholy** [comment]
The point of my question is: if you are using a graphical shell, the error might be triggered by attempting to display the image, not by performing the requested computation.

**Comment by timholy** [comment]
In the "new Images" (getting close now, see #542), the [`ImageCore`](https://github.com/JuliaImages/ImageCore.jl) component has a `rawview` view type that lets you work with 0-255 values more easily. You can read about it in the "latest" documentation.
