### ISSUE TITLE
Histogram Matching

### ISSUE THREAD

**Issue by mronian** [timholy/Images.jl#493]
Making a list of things to implement. Do let me know if anything else can be added :)

- [x] Take two images as input, match histogram of one to other (Gray/Number)
- [x] Take an image, histogram as input and match (Gray/Number)
- [x] Handle Colorants as in #458 
- [x] Handle TransparentColor as in #458

**Comment by mronian** [comment]
For the two image input function, it should handle any combination of images i.e. (Color, Gray) etc. 

@timholy The current version of ```imhist``` simply converts a Colorant Image to ```Gray```. For the above function, I think we should match the histograms of the ```Y``` channel and not the histogram of grayscale versions of the images. What do you think? Does it make sense to have a different ```intensityhist``` function which gives the histogram of the intensity channel? This can then be used with the ```histmatch``` function.

**Comment by mronian** [comment]
Is there any way to get a ```histrange``` with exactly ```nbins``` number of bins? From what I understood, it tries to approximately create ```nbins``` bins but does not necessarily always exactly match that number.

**Comment by timholy** [comment]
Is conversion to Y actually different (other than scale) from conversion to Gray?

`histrange` tries to pick "nice" intervals for the purpose of plotting. If this doesn't really matter (e.g., for algorithmic purposes), then it would be fine to construct the edges by some other means...which means you can definitely control the number of bins.
