### ISSUE TITLE
How to save a gradient map as a grayscale image?

### ISSUE THREAD

**Issue by QingQYang** [timholy/Images.jl#527]
I use the imgradients function to obtain grad_x and grad_y. How can I save the gradient maps as grayscale images in the png format?

**Comment by QingQYang** [comment]
I guess there is some problem with my ImageMagick module in my Mac OS. The save function works in Linux.

**Comment by timholy** [comment]
There's some debugging tips at https://github.com/JuliaIO/ImageMagick.jl, maybe that will help.

**Comment by QingQYang** [comment]
@timholy Thank you!
