### ISSUE TITLE
Change grayim typing to match load output?

### ISSUE THREAD

**Issue by tlnagy** [timholy/Images.jl#556]
I find the following behavior to be a bit inconsistent:

<img width="1118" alt="screen shot 2016-09-13 at 18 18 18" src="https://cloud.githubusercontent.com/assets/1661487/18496869/93193d62-79de-11e6-9b06-b98eb132f75f.png">

while

```julia
julia> show(load("sometiff.tif"))
Gray Images.Image with:
  data: 2048×2044 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},2}
  properties:
    colorspace: Gray
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

```
what's the reason for the difference in typing? Due to this difference it's much easier to run into a situation where `display`ing the first, I am greeted by a giant impenetrable matrix because the `eltype` of the array isn't a subtype of `Colorant` (this check https://github.com/timholy/Images.jl/blob/c12fde02a670e939b4ad75f3d27d5183a65ad268/src/writemime.jl#L6)

**Comment by timholy** [comment]
`grayim` is going away in favor of the approach in [ImageCore](https://juliaimages.github.io/ImageCore.jl/latest/).

**Comment by tlnagy** [comment]
Yeah, I think the `view` everywhere approach is great idea, I'll close this since this is soon to be irrelevant. I'm going to clone `ImageCore` and company and report any issues over there.
