### ISSUE TITLE
pixel values in range 0 to 255?

### ISSUE THREAD

**Issue by udion** [timholy/Images.jl#569]
Is there a way to read the image such that pixel values are UInt in range of 0 to 255 rather that default UFloat 0.0 to 1.0?? Such reading of image will help alot to perform some bit manipulation on the pixel value...
Is there a way to convert the read image in that format?

**Comment by kmsquire** [comment]
See https://github.com/timholy/Images.jl/issues/479#issuecomment-216470719

**Comment by timholy** [comment]
See also http://juliaimages.github.io/latest/conversions_views.html#Views-for-\
