### ISSUE TITLE
Image transform

### ISSUE THREAD

**Issue by SimonDanisch** [timholy/Images.jl#571]
Sorry, I lost a little bit the overview of what is possible with which library.
How do I get the transformed Image from e.g. `m::Mat{3, 3} * Image` ?
Like what I would need for image stitching!
I guess it's fairly straight forward to implement, I just don't want to reinvent the wheel here ;)

Best,
Simon

**Comment by timholy** [comment]
Do you actually mean a spatial transform? The future is CoordinateTransformations.jl (old library: AffineTransforms.jl).

**Comment by SimonDanisch** [comment]
I'm using Interpolations for now, to lookup the distorted image grid ;)
